// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace MythTvApi.Dvr.Dvr.UpdatePlayGroup
{
    /// <summary>
    /// Builds and executes requests for operations under \Dvr\UpdatePlayGroup
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdatePlayGroupRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Dvr.Dvr.UpdatePlayGroup.UpdatePlayGroupRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UpdatePlayGroupRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Dvr/UpdatePlayGroup{?Jump*,Name*,SkipAhead*,SkipBack*,TimeStretch*,TitleMatch*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Dvr.Dvr.UpdatePlayGroup.UpdatePlayGroupRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UpdatePlayGroupRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Dvr/UpdatePlayGroup{?Jump*,Name*,SkipAhead*,SkipBack*,TimeStretch*,TitleMatch*}", rawUrl)
        {
        }
        /// <summary>
        /// POST 
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Dvr.Dvr.UpdatePlayGroup.UpdatePlayGroupPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MythTvApi.Dvr.Dvr.UpdatePlayGroup.UpdatePlayGroupPostResponse?> PostAsUpdatePlayGroupPostResponseAsync(global::MythTvApi.Dvr.Dvr.UpdatePlayGroup.UpdatePlayGroupPostRequestBody body, Action<RequestConfiguration<global::MythTvApi.Dvr.Dvr.UpdatePlayGroup.UpdatePlayGroupRequestBuilder.UpdatePlayGroupRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MythTvApi.Dvr.Dvr.UpdatePlayGroup.UpdatePlayGroupPostResponse> PostAsUpdatePlayGroupPostResponseAsync(global::MythTvApi.Dvr.Dvr.UpdatePlayGroup.UpdatePlayGroupPostRequestBody body, Action<RequestConfiguration<global::MythTvApi.Dvr.Dvr.UpdatePlayGroup.UpdatePlayGroupRequestBuilder.UpdatePlayGroupRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::MythTvApi.Dvr.Dvr.UpdatePlayGroup.UpdatePlayGroupPostResponse>(requestInfo, global::MythTvApi.Dvr.Dvr.UpdatePlayGroup.UpdatePlayGroupPostResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// POST 
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Dvr.Dvr.UpdatePlayGroup.UpdatePlayGroupResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use PostAsUpdatePlayGroupPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MythTvApi.Dvr.Dvr.UpdatePlayGroup.UpdatePlayGroupResponse?> PostAsync(global::MythTvApi.Dvr.Dvr.UpdatePlayGroup.UpdatePlayGroupPostRequestBody body, Action<RequestConfiguration<global::MythTvApi.Dvr.Dvr.UpdatePlayGroup.UpdatePlayGroupRequestBuilder.UpdatePlayGroupRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MythTvApi.Dvr.Dvr.UpdatePlayGroup.UpdatePlayGroupResponse> PostAsync(global::MythTvApi.Dvr.Dvr.UpdatePlayGroup.UpdatePlayGroupPostRequestBody body, Action<RequestConfiguration<global::MythTvApi.Dvr.Dvr.UpdatePlayGroup.UpdatePlayGroupRequestBuilder.UpdatePlayGroupRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::MythTvApi.Dvr.Dvr.UpdatePlayGroup.UpdatePlayGroupResponse>(requestInfo, global::MythTvApi.Dvr.Dvr.UpdatePlayGroup.UpdatePlayGroupResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// POST 
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::MythTvApi.Dvr.Dvr.UpdatePlayGroup.UpdatePlayGroupPostRequestBody body, Action<RequestConfiguration<global::MythTvApi.Dvr.Dvr.UpdatePlayGroup.UpdatePlayGroupRequestBuilder.UpdatePlayGroupRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::MythTvApi.Dvr.Dvr.UpdatePlayGroup.UpdatePlayGroupPostRequestBody body, Action<RequestConfiguration<global::MythTvApi.Dvr.Dvr.UpdatePlayGroup.UpdatePlayGroupRequestBuilder.UpdatePlayGroupRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Dvr.Dvr.UpdatePlayGroup.UpdatePlayGroupRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::MythTvApi.Dvr.Dvr.UpdatePlayGroup.UpdatePlayGroupRequestBuilder WithUrl(string rawUrl)
        {
            return new global::MythTvApi.Dvr.Dvr.UpdatePlayGroup.UpdatePlayGroupRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// POST 
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UpdatePlayGroupRequestBuilderPostQueryParameters 
        {
            public int? Jump { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? Name { get; set; }
#nullable restore
#else
            public string Name { get; set; }
#endif
            public int? SkipAhead { get; set; }
            public int? SkipBack { get; set; }
            public int? TimeStretch { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? TitleMatch { get; set; }
#nullable restore
#else
            public string TitleMatch { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UpdatePlayGroupRequestBuilderPostRequestConfiguration : RequestConfiguration<global::MythTvApi.Dvr.Dvr.UpdatePlayGroup.UpdatePlayGroupRequestBuilder.UpdatePlayGroupRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
