// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using MythTvApi.Content.Models;
using System.Collections.Generic;
using System.IO;
using System;
namespace MythTvApi.Content.Content.GetProgramArtworkList
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetProgramArtworkListGetResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The ArtworkInfo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MythTvApi.Content.Models.ArtworkInfo? ArtworkInfo { get; set; }
#nullable restore
#else
        public global::MythTvApi.Content.Models.ArtworkInfo ArtworkInfo { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Content.Content.GetProgramArtworkList.GetProgramArtworkListGetResponse"/> and sets the default values.
        /// </summary>
        public GetProgramArtworkListGetResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Content.Content.GetProgramArtworkList.GetProgramArtworkListGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MythTvApi.Content.Content.GetProgramArtworkList.GetProgramArtworkListGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MythTvApi.Content.Content.GetProgramArtworkList.GetProgramArtworkListGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "ArtworkInfo", n => { ArtworkInfo = n.GetObjectValue<global::MythTvApi.Content.Models.ArtworkInfo>(global::MythTvApi.Content.Models.ArtworkInfo.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::MythTvApi.Content.Models.ArtworkInfo>("ArtworkInfo", ArtworkInfo);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
