// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace MythTvApi.Dvr.Dvr.ManageJobQueue
{
    /// <summary>
    /// Builds and executes requests for operations under \Dvr\ManageJobQueue
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ManageJobQueueRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Dvr.Dvr.ManageJobQueue.ManageJobQueueRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ManageJobQueueRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Dvr/ManageJobQueue{?Action*,JobArgs*,JobId*,JobName*,JobStartTime*,RecordedId*,RemoteHost*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Dvr.Dvr.ManageJobQueue.ManageJobQueueRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ManageJobQueueRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Dvr/ManageJobQueue{?Action*,JobArgs*,JobId*,JobName*,JobStartTime*,RecordedId*,RemoteHost*}", rawUrl)
        {
        }
        /// <summary>
        /// POST 
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Dvr.Dvr.ManageJobQueue.ManageJobQueuePostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MythTvApi.Dvr.Dvr.ManageJobQueue.ManageJobQueuePostResponse?> PostAsync(global::MythTvApi.Dvr.Dvr.ManageJobQueue.ManageJobQueuePostRequestBody body, Action<RequestConfiguration<global::MythTvApi.Dvr.Dvr.ManageJobQueue.ManageJobQueueRequestBuilder.ManageJobQueueRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MythTvApi.Dvr.Dvr.ManageJobQueue.ManageJobQueuePostResponse> PostAsync(global::MythTvApi.Dvr.Dvr.ManageJobQueue.ManageJobQueuePostRequestBody body, Action<RequestConfiguration<global::MythTvApi.Dvr.Dvr.ManageJobQueue.ManageJobQueueRequestBuilder.ManageJobQueueRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::MythTvApi.Dvr.Dvr.ManageJobQueue.ManageJobQueuePostResponse>(requestInfo, global::MythTvApi.Dvr.Dvr.ManageJobQueue.ManageJobQueuePostResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// POST 
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::MythTvApi.Dvr.Dvr.ManageJobQueue.ManageJobQueuePostRequestBody body, Action<RequestConfiguration<global::MythTvApi.Dvr.Dvr.ManageJobQueue.ManageJobQueueRequestBuilder.ManageJobQueueRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::MythTvApi.Dvr.Dvr.ManageJobQueue.ManageJobQueuePostRequestBody body, Action<RequestConfiguration<global::MythTvApi.Dvr.Dvr.ManageJobQueue.ManageJobQueueRequestBuilder.ManageJobQueueRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Dvr.Dvr.ManageJobQueue.ManageJobQueueRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::MythTvApi.Dvr.Dvr.ManageJobQueue.ManageJobQueueRequestBuilder WithUrl(string rawUrl)
        {
            return new global::MythTvApi.Dvr.Dvr.ManageJobQueue.ManageJobQueueRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// POST 
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ManageJobQueueRequestBuilderPostQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? Action { get; set; }
#nullable restore
#else
            public string Action { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? JobArgs { get; set; }
#nullable restore
#else
            public string JobArgs { get; set; }
#endif
            public int? JobId { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? JobName { get; set; }
#nullable restore
#else
            public string JobName { get; set; }
#endif
            public DateTimeOffset? JobStartTime { get; set; }
            public int? RecordedId { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? RemoteHost { get; set; }
#nullable restore
#else
            public string RemoteHost { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
