// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace MythTvApi.Video.Video.AddVideo
{
    /// <summary>
    /// Builds and executes requests for operations under \Video\AddVideo
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AddVideoRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Video.Video.AddVideo.AddVideoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AddVideoRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Video/AddVideo{?FileName*,HostName*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Video.Video.AddVideo.AddVideoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AddVideoRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Video/AddVideo{?FileName*,HostName*}", rawUrl)
        {
        }
        /// <summary>
        /// POST 
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Video.Video.AddVideo.AddVideoPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MythTvApi.Video.Video.AddVideo.AddVideoPostResponse?> PostAsAddVideoPostResponseAsync(global::MythTvApi.Video.Video.AddVideo.AddVideoPostRequestBody body, Action<RequestConfiguration<global::MythTvApi.Video.Video.AddVideo.AddVideoRequestBuilder.AddVideoRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MythTvApi.Video.Video.AddVideo.AddVideoPostResponse> PostAsAddVideoPostResponseAsync(global::MythTvApi.Video.Video.AddVideo.AddVideoPostRequestBody body, Action<RequestConfiguration<global::MythTvApi.Video.Video.AddVideo.AddVideoRequestBuilder.AddVideoRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::MythTvApi.Video.Video.AddVideo.AddVideoPostResponse>(requestInfo, global::MythTvApi.Video.Video.AddVideo.AddVideoPostResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// POST 
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Video.Video.AddVideo.AddVideoResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use PostAsAddVideoPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MythTvApi.Video.Video.AddVideo.AddVideoResponse?> PostAsync(global::MythTvApi.Video.Video.AddVideo.AddVideoPostRequestBody body, Action<RequestConfiguration<global::MythTvApi.Video.Video.AddVideo.AddVideoRequestBuilder.AddVideoRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MythTvApi.Video.Video.AddVideo.AddVideoResponse> PostAsync(global::MythTvApi.Video.Video.AddVideo.AddVideoPostRequestBody body, Action<RequestConfiguration<global::MythTvApi.Video.Video.AddVideo.AddVideoRequestBuilder.AddVideoRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::MythTvApi.Video.Video.AddVideo.AddVideoResponse>(requestInfo, global::MythTvApi.Video.Video.AddVideo.AddVideoResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// POST 
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::MythTvApi.Video.Video.AddVideo.AddVideoPostRequestBody body, Action<RequestConfiguration<global::MythTvApi.Video.Video.AddVideo.AddVideoRequestBuilder.AddVideoRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::MythTvApi.Video.Video.AddVideo.AddVideoPostRequestBody body, Action<RequestConfiguration<global::MythTvApi.Video.Video.AddVideo.AddVideoRequestBuilder.AddVideoRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Video.Video.AddVideo.AddVideoRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::MythTvApi.Video.Video.AddVideo.AddVideoRequestBuilder WithUrl(string rawUrl)
        {
            return new global::MythTvApi.Video.Video.AddVideo.AddVideoRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// POST 
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AddVideoRequestBuilderPostQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? FileName { get; set; }
#nullable restore
#else
            public string FileName { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? HostName { get; set; }
#nullable restore
#else
            public string HostName { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AddVideoRequestBuilderPostRequestConfiguration : RequestConfiguration<global::MythTvApi.Video.Video.AddVideo.AddVideoRequestBuilder.AddVideoRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
