// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using MythTvApi.Video.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace MythTvApi.Video.Video.GetVideoByFileName
{
    /// <summary>
    /// Builds and executes requests for operations under \Video\GetVideoByFileName
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetVideoByFileNameRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Video.Video.GetVideoByFileName.GetVideoByFileNameRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetVideoByFileNameRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Video/GetVideoByFileName{?FileName*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Video.Video.GetVideoByFileName.GetVideoByFileNameRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetVideoByFileNameRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Video/GetVideoByFileName{?FileName*}", rawUrl)
        {
        }
        /// <summary>
        /// GET 
        /// </summary>
        /// <returns>A List&lt;global::MythTvApi.Video.Models.VideoMetadataInfo&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::MythTvApi.Video.Models.VideoMetadataInfo>?> GetAsync(Action<RequestConfiguration<global::MythTvApi.Video.Video.GetVideoByFileName.GetVideoByFileNameRequestBuilder.GetVideoByFileNameRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::MythTvApi.Video.Models.VideoMetadataInfo>> GetAsync(Action<RequestConfiguration<global::MythTvApi.Video.Video.GetVideoByFileName.GetVideoByFileNameRequestBuilder.GetVideoByFileNameRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::MythTvApi.Video.Models.VideoMetadataInfo>(requestInfo, global::MythTvApi.Video.Models.VideoMetadataInfo.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// GET 
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MythTvApi.Video.Video.GetVideoByFileName.GetVideoByFileNameRequestBuilder.GetVideoByFileNameRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MythTvApi.Video.Video.GetVideoByFileName.GetVideoByFileNameRequestBuilder.GetVideoByFileNameRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Video.Video.GetVideoByFileName.GetVideoByFileNameRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::MythTvApi.Video.Video.GetVideoByFileName.GetVideoByFileNameRequestBuilder WithUrl(string rawUrl)
        {
            return new global::MythTvApi.Video.Video.GetVideoByFileName.GetVideoByFileNameRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// GET 
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GetVideoByFileNameRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? FileName { get; set; }
#nullable restore
#else
            public string FileName { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GetVideoByFileNameRequestBuilderGetRequestConfiguration : RequestConfiguration<global::MythTvApi.Video.Video.GetVideoByFileName.GetVideoByFileNameRequestBuilder.GetVideoByFileNameRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
