// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace MythTvApi.Content.Content.GetPreviewImage
{
    /// <summary>
    /// Builds and executes requests for operations under \Content\GetPreviewImage
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetPreviewImageRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Content.Content.GetPreviewImage.GetPreviewImageRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetPreviewImageRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Content/GetPreviewImage{?ChanId*,Format*,Height*,RecordedId*,SecsIn*,StartTime*,Width*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Content.Content.GetPreviewImage.GetPreviewImageRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetPreviewImageRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Content/GetPreviewImage{?ChanId*,Format*,Height*,RecordedId*,SecsIn*,StartTime*,Width*}", rawUrl)
        {
        }
        /// <summary>
        /// GET 
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Content.Content.GetPreviewImage.GetPreviewImageGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MythTvApi.Content.Content.GetPreviewImage.GetPreviewImageGetResponse?> GetAsync(Action<RequestConfiguration<global::MythTvApi.Content.Content.GetPreviewImage.GetPreviewImageRequestBuilder.GetPreviewImageRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MythTvApi.Content.Content.GetPreviewImage.GetPreviewImageGetResponse> GetAsync(Action<RequestConfiguration<global::MythTvApi.Content.Content.GetPreviewImage.GetPreviewImageRequestBuilder.GetPreviewImageRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::MythTvApi.Content.Content.GetPreviewImage.GetPreviewImageGetResponse>(requestInfo, global::MythTvApi.Content.Content.GetPreviewImage.GetPreviewImageGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// GET 
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MythTvApi.Content.Content.GetPreviewImage.GetPreviewImageRequestBuilder.GetPreviewImageRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MythTvApi.Content.Content.GetPreviewImage.GetPreviewImageRequestBuilder.GetPreviewImageRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Content.Content.GetPreviewImage.GetPreviewImageRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::MythTvApi.Content.Content.GetPreviewImage.GetPreviewImageRequestBuilder WithUrl(string rawUrl)
        {
            return new global::MythTvApi.Content.Content.GetPreviewImage.GetPreviewImageRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// GET 
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GetPreviewImageRequestBuilderGetQueryParameters 
        {
            public int? ChanId { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? Format { get; set; }
#nullable restore
#else
            public string Format { get; set; }
#endif
            public int? Height { get; set; }
            public int? RecordedId { get; set; }
            public int? SecsIn { get; set; }
            public DateTimeOffset? StartTime { get; set; }
            public int? Width { get; set; }
        }
    }
}
#pragma warning restore CS0618
