// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace MythTvApi.Dvr.Dvr.DupInToDescription
{
    /// <summary>
    /// Builds and executes requests for operations under \Dvr\DupInToDescription
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DupInToDescriptionRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Dvr.Dvr.DupInToDescription.DupInToDescriptionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DupInToDescriptionRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Dvr/DupInToDescription{?DupIn*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Dvr.Dvr.DupInToDescription.DupInToDescriptionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DupInToDescriptionRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Dvr/DupInToDescription{?DupIn*}", rawUrl)
        {
        }
        /// <summary>
        /// GET 
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Dvr.Dvr.DupInToDescription.DupInToDescriptionGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MythTvApi.Dvr.Dvr.DupInToDescription.DupInToDescriptionGetResponse?> GetAsDupInToDescriptionGetResponseAsync(Action<RequestConfiguration<global::MythTvApi.Dvr.Dvr.DupInToDescription.DupInToDescriptionRequestBuilder.DupInToDescriptionRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MythTvApi.Dvr.Dvr.DupInToDescription.DupInToDescriptionGetResponse> GetAsDupInToDescriptionGetResponseAsync(Action<RequestConfiguration<global::MythTvApi.Dvr.Dvr.DupInToDescription.DupInToDescriptionRequestBuilder.DupInToDescriptionRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::MythTvApi.Dvr.Dvr.DupInToDescription.DupInToDescriptionGetResponse>(requestInfo, global::MythTvApi.Dvr.Dvr.DupInToDescription.DupInToDescriptionGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// GET 
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Dvr.Dvr.DupInToDescription.DupInToDescriptionResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use GetAsDupInToDescriptionGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MythTvApi.Dvr.Dvr.DupInToDescription.DupInToDescriptionResponse?> GetAsync(Action<RequestConfiguration<global::MythTvApi.Dvr.Dvr.DupInToDescription.DupInToDescriptionRequestBuilder.DupInToDescriptionRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MythTvApi.Dvr.Dvr.DupInToDescription.DupInToDescriptionResponse> GetAsync(Action<RequestConfiguration<global::MythTvApi.Dvr.Dvr.DupInToDescription.DupInToDescriptionRequestBuilder.DupInToDescriptionRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::MythTvApi.Dvr.Dvr.DupInToDescription.DupInToDescriptionResponse>(requestInfo, global::MythTvApi.Dvr.Dvr.DupInToDescription.DupInToDescriptionResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// GET 
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MythTvApi.Dvr.Dvr.DupInToDescription.DupInToDescriptionRequestBuilder.DupInToDescriptionRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MythTvApi.Dvr.Dvr.DupInToDescription.DupInToDescriptionRequestBuilder.DupInToDescriptionRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Dvr.Dvr.DupInToDescription.DupInToDescriptionRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::MythTvApi.Dvr.Dvr.DupInToDescription.DupInToDescriptionRequestBuilder WithUrl(string rawUrl)
        {
            return new global::MythTvApi.Dvr.Dvr.DupInToDescription.DupInToDescriptionRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// GET 
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DupInToDescriptionRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? DupIn { get; set; }
#nullable restore
#else
            public string DupIn { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DupInToDescriptionRequestBuilderGetRequestConfiguration : RequestConfiguration<global::MythTvApi.Dvr.Dvr.DupInToDescription.DupInToDescriptionRequestBuilder.DupInToDescriptionRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
