// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace MythTvApi.Guide.Guide.GetProgramList
{
    /// <summary>
    /// Builds and executes requests for operations under \Guide\GetProgramList
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetProgramListRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Guide.Guide.GetProgramList.GetProgramListRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetProgramListRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Guide/GetProgramList{?CatType*,CategoryFilter*,ChanId*,Count*,Descending*,Details*,EndTime*,GroupBy*,KeywordFilter*,OnlyNew*,PersonFilter*,Sort*,StartIndex*,StartTime*,TitleFilter*,WithInvisible*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Guide.Guide.GetProgramList.GetProgramListRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetProgramListRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Guide/GetProgramList{?CatType*,CategoryFilter*,ChanId*,Count*,Descending*,Details*,EndTime*,GroupBy*,KeywordFilter*,OnlyNew*,PersonFilter*,Sort*,StartIndex*,StartTime*,TitleFilter*,WithInvisible*}", rawUrl)
        {
        }
        /// <summary>
        /// GET 
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Guide.Guide.GetProgramList.GetProgramListGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MythTvApi.Guide.Guide.GetProgramList.GetProgramListGetResponse?> GetAsync(Action<RequestConfiguration<global::MythTvApi.Guide.Guide.GetProgramList.GetProgramListRequestBuilder.GetProgramListRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MythTvApi.Guide.Guide.GetProgramList.GetProgramListGetResponse> GetAsync(Action<RequestConfiguration<global::MythTvApi.Guide.Guide.GetProgramList.GetProgramListRequestBuilder.GetProgramListRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::MythTvApi.Guide.Guide.GetProgramList.GetProgramListGetResponse>(requestInfo, global::MythTvApi.Guide.Guide.GetProgramList.GetProgramListGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// GET 
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MythTvApi.Guide.Guide.GetProgramList.GetProgramListRequestBuilder.GetProgramListRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MythTvApi.Guide.Guide.GetProgramList.GetProgramListRequestBuilder.GetProgramListRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Guide.Guide.GetProgramList.GetProgramListRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::MythTvApi.Guide.Guide.GetProgramList.GetProgramListRequestBuilder WithUrl(string rawUrl)
        {
            return new global::MythTvApi.Guide.Guide.GetProgramList.GetProgramListRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// GET 
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GetProgramListRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? CategoryFilter { get; set; }
#nullable restore
#else
            public string CategoryFilter { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? CatType { get; set; }
#nullable restore
#else
            public string CatType { get; set; }
#endif
            public int? ChanId { get; set; }
            public int? Count { get; set; }
            public bool? Descending { get; set; }
            public bool? Details { get; set; }
            public DateTimeOffset? EndTime { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? GroupBy { get; set; }
#nullable restore
#else
            public string GroupBy { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? KeywordFilter { get; set; }
#nullable restore
#else
            public string KeywordFilter { get; set; }
#endif
            public bool? OnlyNew { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? PersonFilter { get; set; }
#nullable restore
#else
            public string PersonFilter { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? Sort { get; set; }
#nullable restore
#else
            public string Sort { get; set; }
#endif
            public int? StartIndex { get; set; }
            public DateTimeOffset? StartTime { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? TitleFilter { get; set; }
#nullable restore
#else
            public string TitleFilter { get; set; }
#endif
            public bool? WithInvisible { get; set; }
        }
    }
}
#pragma warning restore CS0618
