// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace MythTvApi.Dvr.Dvr.EnableRecordSchedule
{
    /// <summary>
    /// Builds and executes requests for operations under \Dvr\EnableRecordSchedule
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EnableRecordScheduleRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Dvr.Dvr.EnableRecordSchedule.EnableRecordScheduleRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EnableRecordScheduleRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Dvr/EnableRecordSchedule{?RecordId*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Dvr.Dvr.EnableRecordSchedule.EnableRecordScheduleRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EnableRecordScheduleRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Dvr/EnableRecordSchedule{?RecordId*}", rawUrl)
        {
        }
        /// <summary>
        /// POST 
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Dvr.Dvr.EnableRecordSchedule.EnableRecordSchedulePostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MythTvApi.Dvr.Dvr.EnableRecordSchedule.EnableRecordSchedulePostResponse?> PostAsEnableRecordSchedulePostResponseAsync(global::MythTvApi.Dvr.Dvr.EnableRecordSchedule.EnableRecordSchedulePostRequestBody body, Action<RequestConfiguration<global::MythTvApi.Dvr.Dvr.EnableRecordSchedule.EnableRecordScheduleRequestBuilder.EnableRecordScheduleRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MythTvApi.Dvr.Dvr.EnableRecordSchedule.EnableRecordSchedulePostResponse> PostAsEnableRecordSchedulePostResponseAsync(global::MythTvApi.Dvr.Dvr.EnableRecordSchedule.EnableRecordSchedulePostRequestBody body, Action<RequestConfiguration<global::MythTvApi.Dvr.Dvr.EnableRecordSchedule.EnableRecordScheduleRequestBuilder.EnableRecordScheduleRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::MythTvApi.Dvr.Dvr.EnableRecordSchedule.EnableRecordSchedulePostResponse>(requestInfo, global::MythTvApi.Dvr.Dvr.EnableRecordSchedule.EnableRecordSchedulePostResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// POST 
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Dvr.Dvr.EnableRecordSchedule.EnableRecordScheduleResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use PostAsEnableRecordSchedulePostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MythTvApi.Dvr.Dvr.EnableRecordSchedule.EnableRecordScheduleResponse?> PostAsync(global::MythTvApi.Dvr.Dvr.EnableRecordSchedule.EnableRecordSchedulePostRequestBody body, Action<RequestConfiguration<global::MythTvApi.Dvr.Dvr.EnableRecordSchedule.EnableRecordScheduleRequestBuilder.EnableRecordScheduleRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MythTvApi.Dvr.Dvr.EnableRecordSchedule.EnableRecordScheduleResponse> PostAsync(global::MythTvApi.Dvr.Dvr.EnableRecordSchedule.EnableRecordSchedulePostRequestBody body, Action<RequestConfiguration<global::MythTvApi.Dvr.Dvr.EnableRecordSchedule.EnableRecordScheduleRequestBuilder.EnableRecordScheduleRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::MythTvApi.Dvr.Dvr.EnableRecordSchedule.EnableRecordScheduleResponse>(requestInfo, global::MythTvApi.Dvr.Dvr.EnableRecordSchedule.EnableRecordScheduleResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// POST 
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::MythTvApi.Dvr.Dvr.EnableRecordSchedule.EnableRecordSchedulePostRequestBody body, Action<RequestConfiguration<global::MythTvApi.Dvr.Dvr.EnableRecordSchedule.EnableRecordScheduleRequestBuilder.EnableRecordScheduleRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::MythTvApi.Dvr.Dvr.EnableRecordSchedule.EnableRecordSchedulePostRequestBody body, Action<RequestConfiguration<global::MythTvApi.Dvr.Dvr.EnableRecordSchedule.EnableRecordScheduleRequestBuilder.EnableRecordScheduleRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Dvr.Dvr.EnableRecordSchedule.EnableRecordScheduleRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::MythTvApi.Dvr.Dvr.EnableRecordSchedule.EnableRecordScheduleRequestBuilder WithUrl(string rawUrl)
        {
            return new global::MythTvApi.Dvr.Dvr.EnableRecordSchedule.EnableRecordScheduleRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// POST 
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class EnableRecordScheduleRequestBuilderPostQueryParameters 
        {
            public int? RecordId { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class EnableRecordScheduleRequestBuilderPostRequestConfiguration : RequestConfiguration<global::MythTvApi.Dvr.Dvr.EnableRecordSchedule.EnableRecordScheduleRequestBuilder.EnableRecordScheduleRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
