// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using MythTvApi.Video.Video.AddVideo;
using MythTvApi.Video.Video.GetBluray;
using MythTvApi.Video.Video.GetCategoryList;
using MythTvApi.Video.Video.GetLastPlayPos;
using MythTvApi.Video.Video.GetSavedBookmark;
using MythTvApi.Video.Video.GetStreamInfo;
using MythTvApi.Video.Video.GetVideo;
using MythTvApi.Video.Video.GetVideoByFileName;
using MythTvApi.Video.Video.GetVideoCommBreak;
using MythTvApi.Video.Video.GetVideoCutList;
using MythTvApi.Video.Video.GetVideoList;
using MythTvApi.Video.Video.LookupVideo;
using MythTvApi.Video.Video.RemoveVideoFromDB;
using MythTvApi.Video.Video.SetLastPlayPos;
using MythTvApi.Video.Video.SetSavedBookmark;
using MythTvApi.Video.Video.UpdateVideoMetadata;
using MythTvApi.Video.Video.UpdateVideoWatchedStatus;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MythTvApi.Video.Video
{
    /// <summary>
    /// Builds and executes requests for operations under \Video
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class VideoRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The AddVideo property</summary>
        public global::MythTvApi.Video.Video.AddVideo.AddVideoRequestBuilder AddVideo
        {
            get => new global::MythTvApi.Video.Video.AddVideo.AddVideoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetBluray property</summary>
        public global::MythTvApi.Video.Video.GetBluray.GetBlurayRequestBuilder GetBluray
        {
            get => new global::MythTvApi.Video.Video.GetBluray.GetBlurayRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetCategoryList property</summary>
        public global::MythTvApi.Video.Video.GetCategoryList.GetCategoryListRequestBuilder GetCategoryList
        {
            get => new global::MythTvApi.Video.Video.GetCategoryList.GetCategoryListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetLastPlayPos property</summary>
        public global::MythTvApi.Video.Video.GetLastPlayPos.GetLastPlayPosRequestBuilder GetLastPlayPos
        {
            get => new global::MythTvApi.Video.Video.GetLastPlayPos.GetLastPlayPosRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetSavedBookmark property</summary>
        public global::MythTvApi.Video.Video.GetSavedBookmark.GetSavedBookmarkRequestBuilder GetSavedBookmark
        {
            get => new global::MythTvApi.Video.Video.GetSavedBookmark.GetSavedBookmarkRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetStreamInfo property</summary>
        public global::MythTvApi.Video.Video.GetStreamInfo.GetStreamInfoRequestBuilder GetStreamInfo
        {
            get => new global::MythTvApi.Video.Video.GetStreamInfo.GetStreamInfoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetVideo property</summary>
        public global::MythTvApi.Video.Video.GetVideo.GetVideoRequestBuilder GetVideo
        {
            get => new global::MythTvApi.Video.Video.GetVideo.GetVideoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetVideoByFileName property</summary>
        public global::MythTvApi.Video.Video.GetVideoByFileName.GetVideoByFileNameRequestBuilder GetVideoByFileName
        {
            get => new global::MythTvApi.Video.Video.GetVideoByFileName.GetVideoByFileNameRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetVideoCommBreak property</summary>
        public global::MythTvApi.Video.Video.GetVideoCommBreak.GetVideoCommBreakRequestBuilder GetVideoCommBreak
        {
            get => new global::MythTvApi.Video.Video.GetVideoCommBreak.GetVideoCommBreakRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetVideoCutList property</summary>
        public global::MythTvApi.Video.Video.GetVideoCutList.GetVideoCutListRequestBuilder GetVideoCutList
        {
            get => new global::MythTvApi.Video.Video.GetVideoCutList.GetVideoCutListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetVideoList property</summary>
        public global::MythTvApi.Video.Video.GetVideoList.GetVideoListRequestBuilder GetVideoList
        {
            get => new global::MythTvApi.Video.Video.GetVideoList.GetVideoListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The LookupVideo property</summary>
        public global::MythTvApi.Video.Video.LookupVideo.LookupVideoRequestBuilder LookupVideo
        {
            get => new global::MythTvApi.Video.Video.LookupVideo.LookupVideoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The RemoveVideoFromDB property</summary>
        public global::MythTvApi.Video.Video.RemoveVideoFromDB.RemoveVideoFromDBRequestBuilder RemoveVideoFromDB
        {
            get => new global::MythTvApi.Video.Video.RemoveVideoFromDB.RemoveVideoFromDBRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The SetLastPlayPos property</summary>
        public global::MythTvApi.Video.Video.SetLastPlayPos.SetLastPlayPosRequestBuilder SetLastPlayPos
        {
            get => new global::MythTvApi.Video.Video.SetLastPlayPos.SetLastPlayPosRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The SetSavedBookmark property</summary>
        public global::MythTvApi.Video.Video.SetSavedBookmark.SetSavedBookmarkRequestBuilder SetSavedBookmark
        {
            get => new global::MythTvApi.Video.Video.SetSavedBookmark.SetSavedBookmarkRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The UpdateVideoMetadata property</summary>
        public global::MythTvApi.Video.Video.UpdateVideoMetadata.UpdateVideoMetadataRequestBuilder UpdateVideoMetadata
        {
            get => new global::MythTvApi.Video.Video.UpdateVideoMetadata.UpdateVideoMetadataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The UpdateVideoWatchedStatus property</summary>
        public global::MythTvApi.Video.Video.UpdateVideoWatchedStatus.UpdateVideoWatchedStatusRequestBuilder UpdateVideoWatchedStatus
        {
            get => new global::MythTvApi.Video.Video.UpdateVideoWatchedStatus.UpdateVideoWatchedStatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Video.Video.VideoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VideoRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Video", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Video.Video.VideoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VideoRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Video", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
