// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace MythTvApi.Dvr.Dvr.GetRecordedList
{
    /// <summary>
    /// Builds and executes requests for operations under \Dvr\GetRecordedList
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetRecordedListRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Dvr.Dvr.GetRecordedList.GetRecordedListRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetRecordedListRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Dvr/GetRecordedList{?Category*,Count*,Descending*,Details*,IgnoreDeleted*,IgnoreLiveTV*,IncArtWork*,IncCast*,IncChannel*,IncRecording*,RecGroup*,Sort*,StartIndex*,StorageGroup*,TitleRegEx*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Dvr.Dvr.GetRecordedList.GetRecordedListRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetRecordedListRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Dvr/GetRecordedList{?Category*,Count*,Descending*,Details*,IgnoreDeleted*,IgnoreLiveTV*,IncArtWork*,IncCast*,IncChannel*,IncRecording*,RecGroup*,Sort*,StartIndex*,StorageGroup*,TitleRegEx*}", rawUrl)
        {
        }
        /// <summary>
        /// GET 
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Dvr.Dvr.GetRecordedList.GetRecordedListGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MythTvApi.Dvr.Dvr.GetRecordedList.GetRecordedListGetResponse?> GetAsync(Action<RequestConfiguration<global::MythTvApi.Dvr.Dvr.GetRecordedList.GetRecordedListRequestBuilder.GetRecordedListRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MythTvApi.Dvr.Dvr.GetRecordedList.GetRecordedListGetResponse> GetAsync(Action<RequestConfiguration<global::MythTvApi.Dvr.Dvr.GetRecordedList.GetRecordedListRequestBuilder.GetRecordedListRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::MythTvApi.Dvr.Dvr.GetRecordedList.GetRecordedListGetResponse>(requestInfo, global::MythTvApi.Dvr.Dvr.GetRecordedList.GetRecordedListGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// GET 
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MythTvApi.Dvr.Dvr.GetRecordedList.GetRecordedListRequestBuilder.GetRecordedListRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MythTvApi.Dvr.Dvr.GetRecordedList.GetRecordedListRequestBuilder.GetRecordedListRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Dvr.Dvr.GetRecordedList.GetRecordedListRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::MythTvApi.Dvr.Dvr.GetRecordedList.GetRecordedListRequestBuilder WithUrl(string rawUrl)
        {
            return new global::MythTvApi.Dvr.Dvr.GetRecordedList.GetRecordedListRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// GET 
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GetRecordedListRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? Category { get; set; }
#nullable restore
#else
            public string Category { get; set; }
#endif
            public int? Count { get; set; }
            public bool? Descending { get; set; }
            public bool? Details { get; set; }
            public bool? IgnoreDeleted { get; set; }
            public bool? IgnoreLiveTV { get; set; }
            public bool? IncArtWork { get; set; }
            public bool? IncCast { get; set; }
            public bool? IncChannel { get; set; }
            public bool? IncRecording { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? RecGroup { get; set; }
#nullable restore
#else
            public string RecGroup { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? Sort { get; set; }
#nullable restore
#else
            public string Sort { get; set; }
#endif
            public int? StartIndex { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? StorageGroup { get; set; }
#nullable restore
#else
            public string StorageGroup { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? TitleRegEx { get; set; }
#nullable restore
#else
            public string TitleRegEx { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
