// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MythTvApi.Video.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BlurayInfo : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The AACSDetected property</summary>
        public bool? AACSDetected { get; set; }
        /// <summary>The AACSHandled property</summary>
        public bool? AACSHandled { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The AltTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AltTitle { get; set; }
#nullable restore
#else
        public string AltTitle { get; set; }
#endif
        /// <summary>The BDPlusDetected property</summary>
        public bool? BDPlusDetected { get; set; }
        /// <summary>The BDPlusHandled property</summary>
        public bool? BDPlusHandled { get; set; }
        /// <summary>The DiscLang property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DiscLang { get; set; }
#nullable restore
#else
        public string DiscLang { get; set; }
#endif
        /// <summary>The DiscNum property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DiscNum { get; set; }
#nullable restore
#else
        public string DiscNum { get; set; }
#endif
        /// <summary>The FirstPlaySupported property</summary>
        public bool? FirstPlaySupported { get; set; }
        /// <summary>The LibAACSDetected property</summary>
        public bool? LibAACSDetected { get; set; }
        /// <summary>The LibBDPlusDetected property</summary>
        public bool? LibBDPlusDetected { get; set; }
        /// <summary>The NumBDJTitles property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NumBDJTitles { get; set; }
#nullable restore
#else
        public string NumBDJTitles { get; set; }
#endif
        /// <summary>The NumHDMVTitles property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NumHDMVTitles { get; set; }
#nullable restore
#else
        public string NumHDMVTitles { get; set; }
#endif
        /// <summary>The NumUnsupportedTitles property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NumUnsupportedTitles { get; set; }
#nullable restore
#else
        public string NumUnsupportedTitles { get; set; }
#endif
        /// <summary>The Path property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Path { get; set; }
#nullable restore
#else
        public string Path { get; set; }
#endif
        /// <summary>The ThumbCount property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ThumbCount { get; set; }
#nullable restore
#else
        public string ThumbCount { get; set; }
#endif
        /// <summary>The ThumbPath property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ThumbPath { get; set; }
#nullable restore
#else
        public string ThumbPath { get; set; }
#endif
        /// <summary>The Title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The TitleCount property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TitleCount { get; set; }
#nullable restore
#else
        public string TitleCount { get; set; }
#endif
        /// <summary>The TopMenuSupported property</summary>
        public bool? TopMenuSupported { get; set; }
        /// <summary>The TotalDiscNum property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TotalDiscNum { get; set; }
#nullable restore
#else
        public string TotalDiscNum { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Video.Models.BlurayInfo"/> and sets the default values.
        /// </summary>
        public BlurayInfo()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Video.Models.BlurayInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MythTvApi.Video.Models.BlurayInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MythTvApi.Video.Models.BlurayInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AACSDetected", n => { AACSDetected = n.GetBoolValue(); } },
                { "AACSHandled", n => { AACSHandled = n.GetBoolValue(); } },
                { "AltTitle", n => { AltTitle = n.GetStringValue(); } },
                { "BDPlusDetected", n => { BDPlusDetected = n.GetBoolValue(); } },
                { "BDPlusHandled", n => { BDPlusHandled = n.GetBoolValue(); } },
                { "DiscLang", n => { DiscLang = n.GetStringValue(); } },
                { "DiscNum", n => { DiscNum = n.GetStringValue(); } },
                { "FirstPlaySupported", n => { FirstPlaySupported = n.GetBoolValue(); } },
                { "LibAACSDetected", n => { LibAACSDetected = n.GetBoolValue(); } },
                { "LibBDPlusDetected", n => { LibBDPlusDetected = n.GetBoolValue(); } },
                { "NumBDJTitles", n => { NumBDJTitles = n.GetStringValue(); } },
                { "NumHDMVTitles", n => { NumHDMVTitles = n.GetStringValue(); } },
                { "NumUnsupportedTitles", n => { NumUnsupportedTitles = n.GetStringValue(); } },
                { "Path", n => { Path = n.GetStringValue(); } },
                { "ThumbCount", n => { ThumbCount = n.GetStringValue(); } },
                { "ThumbPath", n => { ThumbPath = n.GetStringValue(); } },
                { "Title", n => { Title = n.GetStringValue(); } },
                { "TitleCount", n => { TitleCount = n.GetStringValue(); } },
                { "TopMenuSupported", n => { TopMenuSupported = n.GetBoolValue(); } },
                { "TotalDiscNum", n => { TotalDiscNum = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("AACSDetected", AACSDetected);
            writer.WriteBoolValue("AACSHandled", AACSHandled);
            writer.WriteStringValue("AltTitle", AltTitle);
            writer.WriteBoolValue("BDPlusDetected", BDPlusDetected);
            writer.WriteBoolValue("BDPlusHandled", BDPlusHandled);
            writer.WriteStringValue("DiscLang", DiscLang);
            writer.WriteStringValue("DiscNum", DiscNum);
            writer.WriteBoolValue("FirstPlaySupported", FirstPlaySupported);
            writer.WriteBoolValue("LibAACSDetected", LibAACSDetected);
            writer.WriteBoolValue("LibBDPlusDetected", LibBDPlusDetected);
            writer.WriteStringValue("NumBDJTitles", NumBDJTitles);
            writer.WriteStringValue("NumHDMVTitles", NumHDMVTitles);
            writer.WriteStringValue("NumUnsupportedTitles", NumUnsupportedTitles);
            writer.WriteStringValue("Path", Path);
            writer.WriteStringValue("ThumbCount", ThumbCount);
            writer.WriteStringValue("ThumbPath", ThumbPath);
            writer.WriteStringValue("Title", Title);
            writer.WriteStringValue("TitleCount", TitleCount);
            writer.WriteBoolValue("TopMenuSupported", TopMenuSupported);
            writer.WriteStringValue("TotalDiscNum", TotalDiscNum);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
