// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MythTvApi.Video.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class VideoStreamInfo : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The AspectRatio property</summary>
        public double? AspectRatio { get; set; }
        /// <summary>The AvgFrameRate property</summary>
        public double? AvgFrameRate { get; set; }
        /// <summary>The Channels property</summary>
        public int? Channels { get; set; }
        /// <summary>The CodecName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CodecName { get; set; }
#nullable restore
#else
        public string CodecName { get; set; }
#endif
        /// <summary>The CodecType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CodecType { get; set; }
#nullable restore
#else
        public string CodecType { get; set; }
#endif
        /// <summary>The Duration property</summary>
        public long? Duration { get; set; }
        /// <summary>The FieldOrder property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FieldOrder { get; set; }
#nullable restore
#else
        public string FieldOrder { get; set; }
#endif
        /// <summary>The FrameRate property</summary>
        public double? FrameRate { get; set; }
        /// <summary>The Height property</summary>
        public int? Height { get; set; }
        /// <summary>The Width property</summary>
        public int? Width { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Video.Models.VideoStreamInfo"/> and sets the default values.
        /// </summary>
        public VideoStreamInfo()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Video.Models.VideoStreamInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MythTvApi.Video.Models.VideoStreamInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MythTvApi.Video.Models.VideoStreamInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AspectRatio", n => { AspectRatio = n.GetDoubleValue(); } },
                { "AvgFrameRate", n => { AvgFrameRate = n.GetDoubleValue(); } },
                { "Channels", n => { Channels = n.GetIntValue(); } },
                { "CodecName", n => { CodecName = n.GetStringValue(); } },
                { "CodecType", n => { CodecType = n.GetStringValue(); } },
                { "Duration", n => { Duration = n.GetLongValue(); } },
                { "FieldOrder", n => { FieldOrder = n.GetStringValue(); } },
                { "FrameRate", n => { FrameRate = n.GetDoubleValue(); } },
                { "Height", n => { Height = n.GetIntValue(); } },
                { "Width", n => { Width = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("AspectRatio", AspectRatio);
            writer.WriteDoubleValue("AvgFrameRate", AvgFrameRate);
            writer.WriteIntValue("Channels", Channels);
            writer.WriteStringValue("CodecName", CodecName);
            writer.WriteStringValue("CodecType", CodecType);
            writer.WriteLongValue("Duration", Duration);
            writer.WriteStringValue("FieldOrder", FieldOrder);
            writer.WriteDoubleValue("FrameRate", FrameRate);
            writer.WriteIntValue("Height", Height);
            writer.WriteIntValue("Width", Width);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
