// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MythTvApi.Video.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class VideoStreamInfoList : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The AsOf property</summary>
        public DateTimeOffset? AsOf { get; set; }
        /// <summary>The Count property</summary>
        public int? Count { get; set; }
        /// <summary>The ErrorCode property</summary>
        public int? ErrorCode { get; set; }
        /// <summary>The ErrorMsg property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ErrorMsg { get; set; }
#nullable restore
#else
        public string ErrorMsg { get; set; }
#endif
        /// <summary>The ProtoVer property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProtoVer { get; set; }
#nullable restore
#else
        public string ProtoVer { get; set; }
#endif
        /// <summary>The Version property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Version { get; set; }
#nullable restore
#else
        public string Version { get; set; }
#endif
        /// <summary>The VideoStreamInfos property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MythTvApi.Video.Models.VideoStreamInfo>? VideoStreamInfos { get; set; }
#nullable restore
#else
        public List<global::MythTvApi.Video.Models.VideoStreamInfo> VideoStreamInfos { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Video.Models.VideoStreamInfoList"/> and sets the default values.
        /// </summary>
        public VideoStreamInfoList()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Video.Models.VideoStreamInfoList"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MythTvApi.Video.Models.VideoStreamInfoList CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MythTvApi.Video.Models.VideoStreamInfoList();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AsOf", n => { AsOf = n.GetDateTimeOffsetValue(); } },
                { "Count", n => { Count = n.GetIntValue(); } },
                { "ErrorCode", n => { ErrorCode = n.GetIntValue(); } },
                { "ErrorMsg", n => { ErrorMsg = n.GetStringValue(); } },
                { "ProtoVer", n => { ProtoVer = n.GetStringValue(); } },
                { "Version", n => { Version = n.GetStringValue(); } },
                { "VideoStreamInfos", n => { VideoStreamInfos = n.GetCollectionOfObjectValues<global::MythTvApi.Video.Models.VideoStreamInfo>(global::MythTvApi.Video.Models.VideoStreamInfo.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("AsOf", AsOf);
            writer.WriteIntValue("Count", Count);
            writer.WriteIntValue("ErrorCode", ErrorCode);
            writer.WriteStringValue("ErrorMsg", ErrorMsg);
            writer.WriteStringValue("ProtoVer", ProtoVer);
            writer.WriteStringValue("Version", Version);
            writer.WriteCollectionOfObjectValues<global::MythTvApi.Video.Models.VideoStreamInfo>("VideoStreamInfos", VideoStreamInfos);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
