// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MythTvApi.Video.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class VideoMetadataInfo : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The AddDate property</summary>
        public DateTimeOffset? AddDate { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The Artwork property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MythTvApi.Video.Models.ArtworkInfoList? Artwork { get; set; }
#nullable restore
#else
        public global::MythTvApi.Video.Models.ArtworkInfoList Artwork { get; set; }
#endif
        /// <summary>The Banner property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Banner { get; set; }
#nullable restore
#else
        public string Banner { get; set; }
#endif
        /// <summary>The Cast property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MythTvApi.Video.Models.CastMemberList? Cast { get; set; }
#nullable restore
#else
        public global::MythTvApi.Video.Models.CastMemberList Cast { get; set; }
#endif
        /// <summary>The Category property</summary>
        public int? Category { get; set; }
        /// <summary>The Certification property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Certification { get; set; }
#nullable restore
#else
        public string Certification { get; set; }
#endif
        /// <summary>The ChildID property</summary>
        public int? ChildID { get; set; }
        /// <summary>The Collectionref property</summary>
        public int? Collectionref { get; set; }
        /// <summary>The ContentType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContentType { get; set; }
#nullable restore
#else
        public string ContentType { get; set; }
#endif
        /// <summary>The Coverart property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Coverart { get; set; }
#nullable restore
#else
        public string Coverart { get; set; }
#endif
        /// <summary>The Description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The Director property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Director { get; set; }
#nullable restore
#else
        public string Director { get; set; }
#endif
        /// <summary>The Episode property</summary>
        public int? Episode { get; set; }
        /// <summary>The Fanart property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Fanart { get; set; }
#nullable restore
#else
        public string Fanart { get; set; }
#endif
        /// <summary>The FileName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FileName { get; set; }
#nullable restore
#else
        public string FileName { get; set; }
#endif
        /// <summary>The Genres property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MythTvApi.Video.Models.GenreList? Genres { get; set; }
#nullable restore
#else
        public global::MythTvApi.Video.Models.GenreList Genres { get; set; }
#endif
        /// <summary>The Hash property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Hash { get; set; }
#nullable restore
#else
        public string Hash { get; set; }
#endif
        /// <summary>The HomePage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HomePage { get; set; }
#nullable restore
#else
        public string HomePage { get; set; }
#endif
        /// <summary>The HostName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HostName { get; set; }
#nullable restore
#else
        public string HostName { get; set; }
#endif
        /// <summary>The Id property</summary>
        public int? Id { get; set; }
        /// <summary>The Inetref property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Inetref { get; set; }
#nullable restore
#else
        public string Inetref { get; set; }
#endif
        /// <summary>The Length property</summary>
        public int? Length { get; set; }
        /// <summary>The ParentalLevel property</summary>
        public int? ParentalLevel { get; set; }
        /// <summary>The PlayCount property</summary>
        public int? PlayCount { get; set; }
        /// <summary>The Processed property</summary>
        public bool? Processed { get; set; }
        /// <summary>The ReleaseDate property</summary>
        public DateTimeOffset? ReleaseDate { get; set; }
        /// <summary>The Screenshot property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Screenshot { get; set; }
#nullable restore
#else
        public string Screenshot { get; set; }
#endif
        /// <summary>The Season property</summary>
        public int? Season { get; set; }
        /// <summary>The Studio property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Studio { get; set; }
#nullable restore
#else
        public string Studio { get; set; }
#endif
        /// <summary>The SubTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubTitle { get; set; }
#nullable restore
#else
        public string SubTitle { get; set; }
#endif
        /// <summary>The Tagline property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Tagline { get; set; }
#nullable restore
#else
        public string Tagline { get; set; }
#endif
        /// <summary>The Title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The Trailer property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Trailer { get; set; }
#nullable restore
#else
        public string Trailer { get; set; }
#endif
        /// <summary>The UserRating property</summary>
        public double? UserRating { get; set; }
        /// <summary>The Visible property</summary>
        public bool? Visible { get; set; }
        /// <summary>The Watched property</summary>
        public bool? Watched { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Video.Models.VideoMetadataInfo"/> and sets the default values.
        /// </summary>
        public VideoMetadataInfo()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Video.Models.VideoMetadataInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MythTvApi.Video.Models.VideoMetadataInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MythTvApi.Video.Models.VideoMetadataInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AddDate", n => { AddDate = n.GetDateTimeOffsetValue(); } },
                { "Artwork", n => { Artwork = n.GetObjectValue<global::MythTvApi.Video.Models.ArtworkInfoList>(global::MythTvApi.Video.Models.ArtworkInfoList.CreateFromDiscriminatorValue); } },
                { "Banner", n => { Banner = n.GetStringValue(); } },
                { "Cast", n => { Cast = n.GetObjectValue<global::MythTvApi.Video.Models.CastMemberList>(global::MythTvApi.Video.Models.CastMemberList.CreateFromDiscriminatorValue); } },
                { "Category", n => { Category = n.GetIntValue(); } },
                { "Certification", n => { Certification = n.GetStringValue(); } },
                { "ChildID", n => { ChildID = n.GetIntValue(); } },
                { "Collectionref", n => { Collectionref = n.GetIntValue(); } },
                { "ContentType", n => { ContentType = n.GetStringValue(); } },
                { "Coverart", n => { Coverart = n.GetStringValue(); } },
                { "Description", n => { Description = n.GetStringValue(); } },
                { "Director", n => { Director = n.GetStringValue(); } },
                { "Episode", n => { Episode = n.GetIntValue(); } },
                { "Fanart", n => { Fanart = n.GetStringValue(); } },
                { "FileName", n => { FileName = n.GetStringValue(); } },
                { "Genres", n => { Genres = n.GetObjectValue<global::MythTvApi.Video.Models.GenreList>(global::MythTvApi.Video.Models.GenreList.CreateFromDiscriminatorValue); } },
                { "Hash", n => { Hash = n.GetStringValue(); } },
                { "HomePage", n => { HomePage = n.GetStringValue(); } },
                { "HostName", n => { HostName = n.GetStringValue(); } },
                { "Id", n => { Id = n.GetIntValue(); } },
                { "Inetref", n => { Inetref = n.GetStringValue(); } },
                { "Length", n => { Length = n.GetIntValue(); } },
                { "ParentalLevel", n => { ParentalLevel = n.GetIntValue(); } },
                { "PlayCount", n => { PlayCount = n.GetIntValue(); } },
                { "Processed", n => { Processed = n.GetBoolValue(); } },
                { "ReleaseDate", n => { ReleaseDate = n.GetDateTimeOffsetValue(); } },
                { "Screenshot", n => { Screenshot = n.GetStringValue(); } },
                { "Season", n => { Season = n.GetIntValue(); } },
                { "Studio", n => { Studio = n.GetStringValue(); } },
                { "SubTitle", n => { SubTitle = n.GetStringValue(); } },
                { "Tagline", n => { Tagline = n.GetStringValue(); } },
                { "Title", n => { Title = n.GetStringValue(); } },
                { "Trailer", n => { Trailer = n.GetStringValue(); } },
                { "UserRating", n => { UserRating = n.GetDoubleValue(); } },
                { "Visible", n => { Visible = n.GetBoolValue(); } },
                { "Watched", n => { Watched = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("AddDate", AddDate);
            writer.WriteObjectValue<global::MythTvApi.Video.Models.ArtworkInfoList>("Artwork", Artwork);
            writer.WriteStringValue("Banner", Banner);
            writer.WriteObjectValue<global::MythTvApi.Video.Models.CastMemberList>("Cast", Cast);
            writer.WriteIntValue("Category", Category);
            writer.WriteStringValue("Certification", Certification);
            writer.WriteIntValue("ChildID", ChildID);
            writer.WriteIntValue("Collectionref", Collectionref);
            writer.WriteStringValue("ContentType", ContentType);
            writer.WriteStringValue("Coverart", Coverart);
            writer.WriteStringValue("Description", Description);
            writer.WriteStringValue("Director", Director);
            writer.WriteIntValue("Episode", Episode);
            writer.WriteStringValue("Fanart", Fanart);
            writer.WriteStringValue("FileName", FileName);
            writer.WriteObjectValue<global::MythTvApi.Video.Models.GenreList>("Genres", Genres);
            writer.WriteStringValue("Hash", Hash);
            writer.WriteStringValue("HomePage", HomePage);
            writer.WriteStringValue("HostName", HostName);
            writer.WriteIntValue("Id", Id);
            writer.WriteStringValue("Inetref", Inetref);
            writer.WriteIntValue("Length", Length);
            writer.WriteIntValue("ParentalLevel", ParentalLevel);
            writer.WriteIntValue("PlayCount", PlayCount);
            writer.WriteBoolValue("Processed", Processed);
            writer.WriteDateTimeOffsetValue("ReleaseDate", ReleaseDate);
            writer.WriteStringValue("Screenshot", Screenshot);
            writer.WriteIntValue("Season", Season);
            writer.WriteStringValue("Studio", Studio);
            writer.WriteStringValue("SubTitle", SubTitle);
            writer.WriteStringValue("Tagline", Tagline);
            writer.WriteStringValue("Title", Title);
            writer.WriteStringValue("Trailer", Trailer);
            writer.WriteDoubleValue("UserRating", UserRating);
            writer.WriteBoolValue("Visible", Visible);
            writer.WriteBoolValue("Watched", Watched);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
