// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MythTvApi.Video.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class VideoLookup : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The Artwork property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MythTvApi.Video.Models.ArtworkItem>? Artwork { get; set; }
#nullable restore
#else
        public List<global::MythTvApi.Video.Models.ArtworkItem> Artwork { get; set; }
#endif
        /// <summary>The Budget property</summary>
        public int? Budget { get; set; }
        /// <summary>The Certification property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Certification { get; set; }
#nullable restore
#else
        public string Certification { get; set; }
#endif
        /// <summary>The Collectionref property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Collectionref { get; set; }
#nullable restore
#else
        public string Collectionref { get; set; }
#endif
        /// <summary>The Countries property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Countries { get; set; }
#nullable restore
#else
        public List<string> Countries { get; set; }
#endif
        /// <summary>The Description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The Episode property</summary>
        public int? Episode { get; set; }
        /// <summary>The HomePage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HomePage { get; set; }
#nullable restore
#else
        public string HomePage { get; set; }
#endif
        /// <summary>The IMDB property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IMDB { get; set; }
#nullable restore
#else
        public string IMDB { get; set; }
#endif
        /// <summary>The Inetref property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Inetref { get; set; }
#nullable restore
#else
        public string Inetref { get; set; }
#endif
        /// <summary>The Language property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Language { get; set; }
#nullable restore
#else
        public string Language { get; set; }
#endif
        /// <summary>The Length property</summary>
        public int? Length { get; set; }
        /// <summary>The Popularity property</summary>
        public double? Popularity { get; set; }
        /// <summary>The ReleaseDate property</summary>
        public DateTimeOffset? ReleaseDate { get; set; }
        /// <summary>The Revenue property</summary>
        public int? Revenue { get; set; }
        /// <summary>The Season property</summary>
        public int? Season { get; set; }
        /// <summary>The SubTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubTitle { get; set; }
#nullable restore
#else
        public string SubTitle { get; set; }
#endif
        /// <summary>The Tagline property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Tagline { get; set; }
#nullable restore
#else
        public string Tagline { get; set; }
#endif
        /// <summary>The Title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The TMSRef property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TMSRef { get; set; }
#nullable restore
#else
        public string TMSRef { get; set; }
#endif
        /// <summary>The UserRating property</summary>
        public double? UserRating { get; set; }
        /// <summary>The Year property</summary>
        public int? Year { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Video.Models.VideoLookup"/> and sets the default values.
        /// </summary>
        public VideoLookup()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Video.Models.VideoLookup"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MythTvApi.Video.Models.VideoLookup CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MythTvApi.Video.Models.VideoLookup();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "Artwork", n => { Artwork = n.GetCollectionOfObjectValues<global::MythTvApi.Video.Models.ArtworkItem>(global::MythTvApi.Video.Models.ArtworkItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "Budget", n => { Budget = n.GetIntValue(); } },
                { "Certification", n => { Certification = n.GetStringValue(); } },
                { "Collectionref", n => { Collectionref = n.GetStringValue(); } },
                { "Countries", n => { Countries = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "Description", n => { Description = n.GetStringValue(); } },
                { "Episode", n => { Episode = n.GetIntValue(); } },
                { "HomePage", n => { HomePage = n.GetStringValue(); } },
                { "IMDB", n => { IMDB = n.GetStringValue(); } },
                { "Inetref", n => { Inetref = n.GetStringValue(); } },
                { "Language", n => { Language = n.GetStringValue(); } },
                { "Length", n => { Length = n.GetIntValue(); } },
                { "Popularity", n => { Popularity = n.GetDoubleValue(); } },
                { "ReleaseDate", n => { ReleaseDate = n.GetDateTimeOffsetValue(); } },
                { "Revenue", n => { Revenue = n.GetIntValue(); } },
                { "Season", n => { Season = n.GetIntValue(); } },
                { "SubTitle", n => { SubTitle = n.GetStringValue(); } },
                { "TMSRef", n => { TMSRef = n.GetStringValue(); } },
                { "Tagline", n => { Tagline = n.GetStringValue(); } },
                { "Title", n => { Title = n.GetStringValue(); } },
                { "UserRating", n => { UserRating = n.GetDoubleValue(); } },
                { "Year", n => { Year = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::MythTvApi.Video.Models.ArtworkItem>("Artwork", Artwork);
            writer.WriteIntValue("Budget", Budget);
            writer.WriteStringValue("Certification", Certification);
            writer.WriteStringValue("Collectionref", Collectionref);
            writer.WriteCollectionOfPrimitiveValues<string>("Countries", Countries);
            writer.WriteStringValue("Description", Description);
            writer.WriteIntValue("Episode", Episode);
            writer.WriteStringValue("HomePage", HomePage);
            writer.WriteStringValue("IMDB", IMDB);
            writer.WriteStringValue("Inetref", Inetref);
            writer.WriteStringValue("Language", Language);
            writer.WriteIntValue("Length", Length);
            writer.WriteDoubleValue("Popularity", Popularity);
            writer.WriteDateTimeOffsetValue("ReleaseDate", ReleaseDate);
            writer.WriteIntValue("Revenue", Revenue);
            writer.WriteIntValue("Season", Season);
            writer.WriteStringValue("SubTitle", SubTitle);
            writer.WriteStringValue("Tagline", Tagline);
            writer.WriteStringValue("Title", Title);
            writer.WriteStringValue("TMSRef", TMSRef);
            writer.WriteDoubleValue("UserRating", UserRating);
            writer.WriteIntValue("Year", Year);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
