// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using MythTvApi.Content.Content.DownloadFile;
using MythTvApi.Content.Content.GetAlbumArt;
using MythTvApi.Content.Content.GetDirList;
using MythTvApi.Content.Content.GetFile;
using MythTvApi.Content.Content.GetFileList;
using MythTvApi.Content.Content.GetHash;
using MythTvApi.Content.Content.GetImageFile;
using MythTvApi.Content.Content.GetMusic;
using MythTvApi.Content.Content.GetPreviewImage;
using MythTvApi.Content.Content.GetProgramArtworkList;
using MythTvApi.Content.Content.GetRecording;
using MythTvApi.Content.Content.GetRecordingArtwork;
using MythTvApi.Content.Content.GetRecordingArtworkList;
using MythTvApi.Content.Content.GetVideo;
using MythTvApi.Content.Content.GetVideoArtwork;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MythTvApi.Content.Content
{
    /// <summary>
    /// Builds and executes requests for operations under \Content
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ContentRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The DownloadFile property</summary>
        public global::MythTvApi.Content.Content.DownloadFile.DownloadFileRequestBuilder DownloadFile
        {
            get => new global::MythTvApi.Content.Content.DownloadFile.DownloadFileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetAlbumArt property</summary>
        public global::MythTvApi.Content.Content.GetAlbumArt.GetAlbumArtRequestBuilder GetAlbumArt
        {
            get => new global::MythTvApi.Content.Content.GetAlbumArt.GetAlbumArtRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetDirList property</summary>
        public global::MythTvApi.Content.Content.GetDirList.GetDirListRequestBuilder GetDirList
        {
            get => new global::MythTvApi.Content.Content.GetDirList.GetDirListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetFile property</summary>
        public global::MythTvApi.Content.Content.GetFile.GetFileRequestBuilder GetFile
        {
            get => new global::MythTvApi.Content.Content.GetFile.GetFileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetFileList property</summary>
        public global::MythTvApi.Content.Content.GetFileList.GetFileListRequestBuilder GetFileList
        {
            get => new global::MythTvApi.Content.Content.GetFileList.GetFileListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetHash property</summary>
        public global::MythTvApi.Content.Content.GetHash.GetHashRequestBuilder GetHash
        {
            get => new global::MythTvApi.Content.Content.GetHash.GetHashRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetImageFile property</summary>
        public global::MythTvApi.Content.Content.GetImageFile.GetImageFileRequestBuilder GetImageFile
        {
            get => new global::MythTvApi.Content.Content.GetImageFile.GetImageFileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetMusic property</summary>
        public global::MythTvApi.Content.Content.GetMusic.GetMusicRequestBuilder GetMusic
        {
            get => new global::MythTvApi.Content.Content.GetMusic.GetMusicRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetPreviewImage property</summary>
        public global::MythTvApi.Content.Content.GetPreviewImage.GetPreviewImageRequestBuilder GetPreviewImage
        {
            get => new global::MythTvApi.Content.Content.GetPreviewImage.GetPreviewImageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetProgramArtworkList property</summary>
        public global::MythTvApi.Content.Content.GetProgramArtworkList.GetProgramArtworkListRequestBuilder GetProgramArtworkList
        {
            get => new global::MythTvApi.Content.Content.GetProgramArtworkList.GetProgramArtworkListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetRecording property</summary>
        public global::MythTvApi.Content.Content.GetRecording.GetRecordingRequestBuilder GetRecording
        {
            get => new global::MythTvApi.Content.Content.GetRecording.GetRecordingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetRecordingArtwork property</summary>
        public global::MythTvApi.Content.Content.GetRecordingArtwork.GetRecordingArtworkRequestBuilder GetRecordingArtwork
        {
            get => new global::MythTvApi.Content.Content.GetRecordingArtwork.GetRecordingArtworkRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetRecordingArtworkList property</summary>
        public global::MythTvApi.Content.Content.GetRecordingArtworkList.GetRecordingArtworkListRequestBuilder GetRecordingArtworkList
        {
            get => new global::MythTvApi.Content.Content.GetRecordingArtworkList.GetRecordingArtworkListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetVideo property</summary>
        public global::MythTvApi.Content.Content.GetVideo.GetVideoRequestBuilder GetVideo
        {
            get => new global::MythTvApi.Content.Content.GetVideo.GetVideoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetVideoArtwork property</summary>
        public global::MythTvApi.Content.Content.GetVideoArtwork.GetVideoArtworkRequestBuilder GetVideoArtwork
        {
            get => new global::MythTvApi.Content.Content.GetVideoArtwork.GetVideoArtworkRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Content.Content.ContentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ContentRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Content", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Content.Content.ContentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ContentRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Content", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
