// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace MythTvApi.Dvr.Dvr.RemoveRecorded
{
    /// <summary>
    /// Builds and executes requests for operations under \Dvr\RemoveRecorded
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RemoveRecordedRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Dvr.Dvr.RemoveRecorded.RemoveRecordedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RemoveRecordedRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Dvr/RemoveRecorded{?AllowRerecord*,ChanId*,ForceDelete*,RecordedId*,StartTime*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Dvr.Dvr.RemoveRecorded.RemoveRecordedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RemoveRecordedRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Dvr/RemoveRecorded{?AllowRerecord*,ChanId*,ForceDelete*,RecordedId*,StartTime*}", rawUrl)
        {
        }
        /// <summary>
        /// POST 
        /// </summary>
        /// <returns>A List&lt;bool&gt;</returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<bool?>?> PostAsync(global::MythTvApi.Dvr.Dvr.RemoveRecorded.RemoveRecordedPostRequestBody body, Action<RequestConfiguration<global::MythTvApi.Dvr.Dvr.RemoveRecorded.RemoveRecordedRequestBuilder.RemoveRecordedRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<bool?>> PostAsync(global::MythTvApi.Dvr.Dvr.RemoveRecorded.RemoveRecordedPostRequestBody body, Action<RequestConfiguration<global::MythTvApi.Dvr.Dvr.RemoveRecorded.RemoveRecordedRequestBuilder.RemoveRecordedRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var collectionResult = await RequestAdapter.SendPrimitiveCollectionAsync<bool?>(requestInfo, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// POST 
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::MythTvApi.Dvr.Dvr.RemoveRecorded.RemoveRecordedPostRequestBody body, Action<RequestConfiguration<global::MythTvApi.Dvr.Dvr.RemoveRecorded.RemoveRecordedRequestBuilder.RemoveRecordedRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::MythTvApi.Dvr.Dvr.RemoveRecorded.RemoveRecordedPostRequestBody body, Action<RequestConfiguration<global::MythTvApi.Dvr.Dvr.RemoveRecorded.RemoveRecordedRequestBuilder.RemoveRecordedRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Dvr.Dvr.RemoveRecorded.RemoveRecordedRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::MythTvApi.Dvr.Dvr.RemoveRecorded.RemoveRecordedRequestBuilder WithUrl(string rawUrl)
        {
            return new global::MythTvApi.Dvr.Dvr.RemoveRecorded.RemoveRecordedRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// POST 
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RemoveRecordedRequestBuilderPostQueryParameters 
        {
            public bool? AllowRerecord { get; set; }
            public int? ChanId { get; set; }
            public bool? ForceDelete { get; set; }
            public int? RecordedId { get; set; }
            public DateTimeOffset? StartTime { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RemoveRecordedRequestBuilderPostRequestConfiguration : RequestConfiguration<global::MythTvApi.Dvr.Dvr.RemoveRecorded.RemoveRecordedRequestBuilder.RemoveRecordedRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
