// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MythTvApi.Guide.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ChannelInfo : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The ATSCMajorChan property</summary>
        public int? ATSCMajorChan { get; set; }
        /// <summary>The ATSCMinorChan property</summary>
        public int? ATSCMinorChan { get; set; }
        /// <summary>The CallSign property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CallSign { get; set; }
#nullable restore
#else
        public string CallSign { get; set; }
#endif
        /// <summary>The ChanFilters property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChanFilters { get; set; }
#nullable restore
#else
        public string ChanFilters { get; set; }
#endif
        /// <summary>The ChanId property</summary>
        public int? ChanId { get; set; }
        /// <summary>The ChannelGroups property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChannelGroups { get; set; }
#nullable restore
#else
        public string ChannelGroups { get; set; }
#endif
        /// <summary>The ChannelName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChannelName { get; set; }
#nullable restore
#else
        public string ChannelName { get; set; }
#endif
        /// <summary>The ChanNum property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChanNum { get; set; }
#nullable restore
#else
        public string ChanNum { get; set; }
#endif
        /// <summary>The CommFree property</summary>
        public bool? CommFree { get; set; }
        /// <summary>The CommMethod property</summary>
        public int? CommMethod { get; set; }
        /// <summary>The DefaultAuth property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultAuth { get; set; }
#nullable restore
#else
        public string DefaultAuth { get; set; }
#endif
        /// <summary>The ExtendedVisible property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExtendedVisible { get; set; }
#nullable restore
#else
        public string ExtendedVisible { get; set; }
#endif
        /// <summary>The FineTune property</summary>
        public int? FineTune { get; set; }
        /// <summary>The Format property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Format { get; set; }
#nullable restore
#else
        public string Format { get; set; }
#endif
        /// <summary>The FrequencyId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FrequencyId { get; set; }
#nullable restore
#else
        public string FrequencyId { get; set; }
#endif
        /// <summary>The Icon property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Icon { get; set; }
#nullable restore
#else
        public string Icon { get; set; }
#endif
        /// <summary>The IconURL property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IconURL { get; set; }
#nullable restore
#else
        public string IconURL { get; set; }
#endif
        /// <summary>The InputId property</summary>
        public int? InputId { get; set; }
        /// <summary>The Inputs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Inputs { get; set; }
#nullable restore
#else
        public string Inputs { get; set; }
#endif
        /// <summary>The MplexId property</summary>
        public int? MplexId { get; set; }
        /// <summary>The Programs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MythTvApi.Guide.Models.Program>? Programs { get; set; }
#nullable restore
#else
        public List<global::MythTvApi.Guide.Models.Program> Programs { get; set; }
#endif
        /// <summary>The RecPriority property</summary>
        public int? RecPriority { get; set; }
        /// <summary>The ServiceId property</summary>
        public int? ServiceId { get; set; }
        /// <summary>The ServiceType property</summary>
        public int? ServiceType { get; set; }
        /// <summary>The SourceId property</summary>
        public int? SourceId { get; set; }
        /// <summary>The TimeOffset property</summary>
        public int? TimeOffset { get; set; }
        /// <summary>The UseEIT property</summary>
        public bool? UseEIT { get; set; }
        /// <summary>The Visible property</summary>
        public bool? Visible { get; set; }
        /// <summary>The XMLTVID property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? XMLTVID { get; set; }
#nullable restore
#else
        public string XMLTVID { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Guide.Models.ChannelInfo"/> and sets the default values.
        /// </summary>
        public ChannelInfo()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Guide.Models.ChannelInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MythTvApi.Guide.Models.ChannelInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MythTvApi.Guide.Models.ChannelInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "ATSCMajorChan", n => { ATSCMajorChan = n.GetIntValue(); } },
                { "ATSCMinorChan", n => { ATSCMinorChan = n.GetIntValue(); } },
                { "CallSign", n => { CallSign = n.GetStringValue(); } },
                { "ChanFilters", n => { ChanFilters = n.GetStringValue(); } },
                { "ChanId", n => { ChanId = n.GetIntValue(); } },
                { "ChanNum", n => { ChanNum = n.GetStringValue(); } },
                { "ChannelGroups", n => { ChannelGroups = n.GetStringValue(); } },
                { "ChannelName", n => { ChannelName = n.GetStringValue(); } },
                { "CommFree", n => { CommFree = n.GetBoolValue(); } },
                { "CommMethod", n => { CommMethod = n.GetIntValue(); } },
                { "DefaultAuth", n => { DefaultAuth = n.GetStringValue(); } },
                { "ExtendedVisible", n => { ExtendedVisible = n.GetStringValue(); } },
                { "FineTune", n => { FineTune = n.GetIntValue(); } },
                { "Format", n => { Format = n.GetStringValue(); } },
                { "FrequencyId", n => { FrequencyId = n.GetStringValue(); } },
                { "Icon", n => { Icon = n.GetStringValue(); } },
                { "IconURL", n => { IconURL = n.GetStringValue(); } },
                { "InputId", n => { InputId = n.GetIntValue(); } },
                { "Inputs", n => { Inputs = n.GetStringValue(); } },
                { "MplexId", n => { MplexId = n.GetIntValue(); } },
                { "Programs", n => { Programs = n.GetCollectionOfObjectValues<global::MythTvApi.Guide.Models.Program>(global::MythTvApi.Guide.Models.Program.CreateFromDiscriminatorValue)?.AsList(); } },
                { "RecPriority", n => { RecPriority = n.GetIntValue(); } },
                { "ServiceId", n => { ServiceId = n.GetIntValue(); } },
                { "ServiceType", n => { ServiceType = n.GetIntValue(); } },
                { "SourceId", n => { SourceId = n.GetIntValue(); } },
                { "TimeOffset", n => { TimeOffset = n.GetIntValue(); } },
                { "UseEIT", n => { UseEIT = n.GetBoolValue(); } },
                { "Visible", n => { Visible = n.GetBoolValue(); } },
                { "XMLTVID", n => { XMLTVID = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("ATSCMajorChan", ATSCMajorChan);
            writer.WriteIntValue("ATSCMinorChan", ATSCMinorChan);
            writer.WriteStringValue("CallSign", CallSign);
            writer.WriteStringValue("ChanFilters", ChanFilters);
            writer.WriteIntValue("ChanId", ChanId);
            writer.WriteStringValue("ChannelGroups", ChannelGroups);
            writer.WriteStringValue("ChannelName", ChannelName);
            writer.WriteStringValue("ChanNum", ChanNum);
            writer.WriteBoolValue("CommFree", CommFree);
            writer.WriteIntValue("CommMethod", CommMethod);
            writer.WriteStringValue("DefaultAuth", DefaultAuth);
            writer.WriteStringValue("ExtendedVisible", ExtendedVisible);
            writer.WriteIntValue("FineTune", FineTune);
            writer.WriteStringValue("Format", Format);
            writer.WriteStringValue("FrequencyId", FrequencyId);
            writer.WriteStringValue("Icon", Icon);
            writer.WriteStringValue("IconURL", IconURL);
            writer.WriteIntValue("InputId", InputId);
            writer.WriteStringValue("Inputs", Inputs);
            writer.WriteIntValue("MplexId", MplexId);
            writer.WriteCollectionOfObjectValues<global::MythTvApi.Guide.Models.Program>("Programs", Programs);
            writer.WriteIntValue("RecPriority", RecPriority);
            writer.WriteIntValue("ServiceId", ServiceId);
            writer.WriteIntValue("ServiceType", ServiceType);
            writer.WriteIntValue("SourceId", SourceId);
            writer.WriteIntValue("TimeOffset", TimeOffset);
            writer.WriteBoolValue("UseEIT", UseEIT);
            writer.WriteBoolValue("Visible", Visible);
            writer.WriteStringValue("XMLTVID", XMLTVID);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
