// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MythTvApi.Guide.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RecordingInfo : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The DupInType property</summary>
        public int? DupInType { get; set; }
        /// <summary>The DupMethod property</summary>
        public int? DupMethod { get; set; }
        /// <summary>The EncoderId property</summary>
        public int? EncoderId { get; set; }
        /// <summary>The EncoderName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EncoderName { get; set; }
#nullable restore
#else
        public string EncoderName { get; set; }
#endif
        /// <summary>The EndTs property</summary>
        public DateTimeOffset? EndTs { get; set; }
        /// <summary>The FileName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FileName { get; set; }
#nullable restore
#else
        public string FileName { get; set; }
#endif
        /// <summary>The FileSize property</summary>
        public long? FileSize { get; set; }
        /// <summary>The HostName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HostName { get; set; }
#nullable restore
#else
        public string HostName { get; set; }
#endif
        /// <summary>The LastModified property</summary>
        public DateTimeOffset? LastModified { get; set; }
        /// <summary>The PlayGroup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlayGroup { get; set; }
#nullable restore
#else
        public string PlayGroup { get; set; }
#endif
        /// <summary>The Priority property</summary>
        public int? Priority { get; set; }
        /// <summary>The Profile property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Profile { get; set; }
#nullable restore
#else
        public string Profile { get; set; }
#endif
        /// <summary>The RecGroup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RecGroup { get; set; }
#nullable restore
#else
        public string RecGroup { get; set; }
#endif
        /// <summary>The RecordedId property</summary>
        public int? RecordedId { get; set; }
        /// <summary>The RecordId property</summary>
        public int? RecordId { get; set; }
        /// <summary>The RecType property</summary>
        public int? RecType { get; set; }
        /// <summary>The RecTypeStatus property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RecTypeStatus { get; set; }
#nullable restore
#else
        public string RecTypeStatus { get; set; }
#endif
        /// <summary>The StartTs property</summary>
        public DateTimeOffset? StartTs { get; set; }
        /// <summary>The Status property</summary>
        public int? Status { get; set; }
        /// <summary>The StatusName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusName { get; set; }
#nullable restore
#else
        public string StatusName { get; set; }
#endif
        /// <summary>The StorageGroup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StorageGroup { get; set; }
#nullable restore
#else
        public string StorageGroup { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Guide.Models.RecordingInfo"/> and sets the default values.
        /// </summary>
        public RecordingInfo()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Guide.Models.RecordingInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MythTvApi.Guide.Models.RecordingInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MythTvApi.Guide.Models.RecordingInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "DupInType", n => { DupInType = n.GetIntValue(); } },
                { "DupMethod", n => { DupMethod = n.GetIntValue(); } },
                { "EncoderId", n => { EncoderId = n.GetIntValue(); } },
                { "EncoderName", n => { EncoderName = n.GetStringValue(); } },
                { "EndTs", n => { EndTs = n.GetDateTimeOffsetValue(); } },
                { "FileName", n => { FileName = n.GetStringValue(); } },
                { "FileSize", n => { FileSize = n.GetLongValue(); } },
                { "HostName", n => { HostName = n.GetStringValue(); } },
                { "LastModified", n => { LastModified = n.GetDateTimeOffsetValue(); } },
                { "PlayGroup", n => { PlayGroup = n.GetStringValue(); } },
                { "Priority", n => { Priority = n.GetIntValue(); } },
                { "Profile", n => { Profile = n.GetStringValue(); } },
                { "RecGroup", n => { RecGroup = n.GetStringValue(); } },
                { "RecType", n => { RecType = n.GetIntValue(); } },
                { "RecTypeStatus", n => { RecTypeStatus = n.GetStringValue(); } },
                { "RecordId", n => { RecordId = n.GetIntValue(); } },
                { "RecordedId", n => { RecordedId = n.GetIntValue(); } },
                { "StartTs", n => { StartTs = n.GetDateTimeOffsetValue(); } },
                { "Status", n => { Status = n.GetIntValue(); } },
                { "StatusName", n => { StatusName = n.GetStringValue(); } },
                { "StorageGroup", n => { StorageGroup = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("DupInType", DupInType);
            writer.WriteIntValue("DupMethod", DupMethod);
            writer.WriteIntValue("EncoderId", EncoderId);
            writer.WriteStringValue("EncoderName", EncoderName);
            writer.WriteDateTimeOffsetValue("EndTs", EndTs);
            writer.WriteStringValue("FileName", FileName);
            writer.WriteLongValue("FileSize", FileSize);
            writer.WriteStringValue("HostName", HostName);
            writer.WriteDateTimeOffsetValue("LastModified", LastModified);
            writer.WriteStringValue("PlayGroup", PlayGroup);
            writer.WriteIntValue("Priority", Priority);
            writer.WriteStringValue("Profile", Profile);
            writer.WriteStringValue("RecGroup", RecGroup);
            writer.WriteIntValue("RecordedId", RecordedId);
            writer.WriteIntValue("RecordId", RecordId);
            writer.WriteIntValue("RecType", RecType);
            writer.WriteStringValue("RecTypeStatus", RecTypeStatus);
            writer.WriteDateTimeOffsetValue("StartTs", StartTs);
            writer.WriteIntValue("Status", Status);
            writer.WriteStringValue("StatusName", StatusName);
            writer.WriteStringValue("StorageGroup", StorageGroup);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
