// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MythTvApi.Dvr.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Encoder : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The Connected property</summary>
        public bool? Connected { get; set; }
        /// <summary>The HostName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HostName { get; set; }
#nullable restore
#else
        public string HostName { get; set; }
#endif
        /// <summary>The Id property</summary>
        public int? Id { get; set; }
        /// <summary>The Inputs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MythTvApi.Dvr.Models.Input>? Inputs { get; set; }
#nullable restore
#else
        public List<global::MythTvApi.Dvr.Models.Input> Inputs { get; set; }
#endif
        /// <summary>The Local property</summary>
        public bool? Local { get; set; }
        /// <summary>The LowOnFreeSpace property</summary>
        public bool? LowOnFreeSpace { get; set; }
        /// <summary>The Recording property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MythTvApi.Dvr.Models.Program? Recording { get; set; }
#nullable restore
#else
        public global::MythTvApi.Dvr.Models.Program Recording { get; set; }
#endif
        /// <summary>The SleepStatus property</summary>
        public int? SleepStatus { get; set; }
        /// <summary>The State property</summary>
        public int? State { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Dvr.Models.Encoder"/> and sets the default values.
        /// </summary>
        public Encoder()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Dvr.Models.Encoder"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MythTvApi.Dvr.Models.Encoder CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MythTvApi.Dvr.Models.Encoder();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "Connected", n => { Connected = n.GetBoolValue(); } },
                { "HostName", n => { HostName = n.GetStringValue(); } },
                { "Id", n => { Id = n.GetIntValue(); } },
                { "Inputs", n => { Inputs = n.GetCollectionOfObjectValues<global::MythTvApi.Dvr.Models.Input>(global::MythTvApi.Dvr.Models.Input.CreateFromDiscriminatorValue)?.AsList(); } },
                { "Local", n => { Local = n.GetBoolValue(); } },
                { "LowOnFreeSpace", n => { LowOnFreeSpace = n.GetBoolValue(); } },
                { "Recording", n => { Recording = n.GetObjectValue<global::MythTvApi.Dvr.Models.Program>(global::MythTvApi.Dvr.Models.Program.CreateFromDiscriminatorValue); } },
                { "SleepStatus", n => { SleepStatus = n.GetIntValue(); } },
                { "State", n => { State = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("Connected", Connected);
            writer.WriteStringValue("HostName", HostName);
            writer.WriteIntValue("Id", Id);
            writer.WriteCollectionOfObjectValues<global::MythTvApi.Dvr.Models.Input>("Inputs", Inputs);
            writer.WriteBoolValue("Local", Local);
            writer.WriteBoolValue("LowOnFreeSpace", LowOnFreeSpace);
            writer.WriteObjectValue<global::MythTvApi.Dvr.Models.Program>("Recording", Recording);
            writer.WriteIntValue("SleepStatus", SleepStatus);
            writer.WriteIntValue("State", State);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
