// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MythTvApi.Dvr.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Input : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The CardId property</summary>
        public int? CardId { get; set; }
        /// <summary>The DisplayName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>The Id property</summary>
        public int? Id { get; set; }
        /// <summary>The InputName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InputName { get; set; }
#nullable restore
#else
        public string InputName { get; set; }
#endif
        /// <summary>The LiveTVOrder property</summary>
        public int? LiveTVOrder { get; set; }
        /// <summary>The QuickTune property</summary>
        public bool? QuickTune { get; set; }
        /// <summary>The RecPriority property</summary>
        public int? RecPriority { get; set; }
        /// <summary>The ScheduleOrder property</summary>
        public int? ScheduleOrder { get; set; }
        /// <summary>The SourceId property</summary>
        public int? SourceId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Dvr.Models.Input"/> and sets the default values.
        /// </summary>
        public Input()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Dvr.Models.Input"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MythTvApi.Dvr.Models.Input CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MythTvApi.Dvr.Models.Input();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "CardId", n => { CardId = n.GetIntValue(); } },
                { "DisplayName", n => { DisplayName = n.GetStringValue(); } },
                { "Id", n => { Id = n.GetIntValue(); } },
                { "InputName", n => { InputName = n.GetStringValue(); } },
                { "LiveTVOrder", n => { LiveTVOrder = n.GetIntValue(); } },
                { "QuickTune", n => { QuickTune = n.GetBoolValue(); } },
                { "RecPriority", n => { RecPriority = n.GetIntValue(); } },
                { "ScheduleOrder", n => { ScheduleOrder = n.GetIntValue(); } },
                { "SourceId", n => { SourceId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("CardId", CardId);
            writer.WriteStringValue("DisplayName", DisplayName);
            writer.WriteIntValue("Id", Id);
            writer.WriteStringValue("InputName", InputName);
            writer.WriteIntValue("LiveTVOrder", LiveTVOrder);
            writer.WriteBoolValue("QuickTune", QuickTune);
            writer.WriteIntValue("RecPriority", RecPriority);
            writer.WriteIntValue("ScheduleOrder", ScheduleOrder);
            writer.WriteIntValue("SourceId", SourceId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
