// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MythTvApi.Dvr.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PlayGroup : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The Jump property</summary>
        public int? Jump { get; set; }
        /// <summary>The Name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The SkipAhead property</summary>
        public int? SkipAhead { get; set; }
        /// <summary>The SkipBack property</summary>
        public int? SkipBack { get; set; }
        /// <summary>The TimeStretch property</summary>
        public int? TimeStretch { get; set; }
        /// <summary>The TitleMatch property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TitleMatch { get; set; }
#nullable restore
#else
        public string TitleMatch { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Dvr.Models.PlayGroup"/> and sets the default values.
        /// </summary>
        public PlayGroup()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Dvr.Models.PlayGroup"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MythTvApi.Dvr.Models.PlayGroup CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MythTvApi.Dvr.Models.PlayGroup();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "Jump", n => { Jump = n.GetIntValue(); } },
                { "Name", n => { Name = n.GetStringValue(); } },
                { "SkipAhead", n => { SkipAhead = n.GetIntValue(); } },
                { "SkipBack", n => { SkipBack = n.GetIntValue(); } },
                { "TimeStretch", n => { TimeStretch = n.GetIntValue(); } },
                { "TitleMatch", n => { TitleMatch = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("Jump", Jump);
            writer.WriteStringValue("Name", Name);
            writer.WriteIntValue("SkipAhead", SkipAhead);
            writer.WriteIntValue("SkipBack", SkipBack);
            writer.WriteIntValue("TimeStretch", TimeStretch);
            writer.WriteStringValue("TitleMatch", TitleMatch);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
