// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace MythTvApi.Dvr.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Program : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The Airdate property</summary>
        public Date? Airdate { get; set; }
        /// <summary>The Artwork property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MythTvApi.Dvr.Models.ArtworkInfoList? Artwork { get; set; }
#nullable restore
#else
        public global::MythTvApi.Dvr.Models.ArtworkInfoList Artwork { get; set; }
#endif
        /// <summary>The AudioPropNames property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AudioPropNames { get; set; }
#nullable restore
#else
        public string AudioPropNames { get; set; }
#endif
        /// <summary>The AudioProps property</summary>
        public int? AudioProps { get; set; }
        /// <summary>The Cast property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MythTvApi.Dvr.Models.CastMemberList? Cast { get; set; }
#nullable restore
#else
        public global::MythTvApi.Dvr.Models.CastMemberList Cast { get; set; }
#endif
        /// <summary>The Category property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Category { get; set; }
#nullable restore
#else
        public string Category { get; set; }
#endif
        /// <summary>The CatType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CatType { get; set; }
#nullable restore
#else
        public string CatType { get; set; }
#endif
        /// <summary>The Channel property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MythTvApi.Dvr.Models.ChannelInfo? Channel { get; set; }
#nullable restore
#else
        public global::MythTvApi.Dvr.Models.ChannelInfo Channel { get; set; }
#endif
        /// <summary>The Description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The EndTime property</summary>
        public DateTimeOffset? EndTime { get; set; }
        /// <summary>The Episode property</summary>
        public int? Episode { get; set; }
        /// <summary>The FileName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FileName { get; set; }
#nullable restore
#else
        public string FileName { get; set; }
#endif
        /// <summary>The FileSize property</summary>
        public long? FileSize { get; set; }
        /// <summary>The HostName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HostName { get; set; }
#nullable restore
#else
        public string HostName { get; set; }
#endif
        /// <summary>The Inetref property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Inetref { get; set; }
#nullable restore
#else
        public string Inetref { get; set; }
#endif
        /// <summary>The LastModified property</summary>
        public DateTimeOffset? LastModified { get; set; }
        /// <summary>The ProgramFlagNames property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProgramFlagNames { get; set; }
#nullable restore
#else
        public string ProgramFlagNames { get; set; }
#endif
        /// <summary>The ProgramFlags property</summary>
        public int? ProgramFlags { get; set; }
        /// <summary>The ProgramId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProgramId { get; set; }
#nullable restore
#else
        public string ProgramId { get; set; }
#endif
        /// <summary>The Recording property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MythTvApi.Dvr.Models.RecordingInfo? Recording { get; set; }
#nullable restore
#else
        public global::MythTvApi.Dvr.Models.RecordingInfo Recording { get; set; }
#endif
        /// <summary>The ReleaseYear property</summary>
        public int? ReleaseYear { get; set; }
        /// <summary>The Repeat property</summary>
        public bool? Repeat { get; set; }
        /// <summary>The Season property</summary>
        public int? Season { get; set; }
        /// <summary>The SeriesId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SeriesId { get; set; }
#nullable restore
#else
        public string SeriesId { get; set; }
#endif
        /// <summary>The Stars property</summary>
        public double? Stars { get; set; }
        /// <summary>The StartTime property</summary>
        public DateTimeOffset? StartTime { get; set; }
        /// <summary>The SubPropNames property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubPropNames { get; set; }
#nullable restore
#else
        public string SubPropNames { get; set; }
#endif
        /// <summary>The SubProps property</summary>
        public int? SubProps { get; set; }
        /// <summary>The SubTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubTitle { get; set; }
#nullable restore
#else
        public string SubTitle { get; set; }
#endif
        /// <summary>The Title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The TotalEpisodes property</summary>
        public int? TotalEpisodes { get; set; }
        /// <summary>The VideoPropNames property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VideoPropNames { get; set; }
#nullable restore
#else
        public string VideoPropNames { get; set; }
#endif
        /// <summary>The VideoProps property</summary>
        public int? VideoProps { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Dvr.Models.Program"/> and sets the default values.
        /// </summary>
        public Program()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Dvr.Models.Program"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MythTvApi.Dvr.Models.Program CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MythTvApi.Dvr.Models.Program();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "Airdate", n => { Airdate = n.GetDateValue(); } },
                { "Artwork", n => { Artwork = n.GetObjectValue<global::MythTvApi.Dvr.Models.ArtworkInfoList>(global::MythTvApi.Dvr.Models.ArtworkInfoList.CreateFromDiscriminatorValue); } },
                { "AudioPropNames", n => { AudioPropNames = n.GetStringValue(); } },
                { "AudioProps", n => { AudioProps = n.GetIntValue(); } },
                { "Cast", n => { Cast = n.GetObjectValue<global::MythTvApi.Dvr.Models.CastMemberList>(global::MythTvApi.Dvr.Models.CastMemberList.CreateFromDiscriminatorValue); } },
                { "CatType", n => { CatType = n.GetStringValue(); } },
                { "Category", n => { Category = n.GetStringValue(); } },
                { "Channel", n => { Channel = n.GetObjectValue<global::MythTvApi.Dvr.Models.ChannelInfo>(global::MythTvApi.Dvr.Models.ChannelInfo.CreateFromDiscriminatorValue); } },
                { "Description", n => { Description = n.GetStringValue(); } },
                { "EndTime", n => { EndTime = n.GetDateTimeOffsetValue(); } },
                { "Episode", n => { Episode = n.GetIntValue(); } },
                { "FileName", n => { FileName = n.GetStringValue(); } },
                { "FileSize", n => { FileSize = n.GetLongValue(); } },
                { "HostName", n => { HostName = n.GetStringValue(); } },
                { "Inetref", n => { Inetref = n.GetStringValue(); } },
                { "LastModified", n => { LastModified = n.GetDateTimeOffsetValue(); } },
                { "ProgramFlagNames", n => { ProgramFlagNames = n.GetStringValue(); } },
                { "ProgramFlags", n => { ProgramFlags = n.GetIntValue(); } },
                { "ProgramId", n => { ProgramId = n.GetStringValue(); } },
                { "Recording", n => { Recording = n.GetObjectValue<global::MythTvApi.Dvr.Models.RecordingInfo>(global::MythTvApi.Dvr.Models.RecordingInfo.CreateFromDiscriminatorValue); } },
                { "ReleaseYear", n => { ReleaseYear = n.GetIntValue(); } },
                { "Repeat", n => { Repeat = n.GetBoolValue(); } },
                { "Season", n => { Season = n.GetIntValue(); } },
                { "SeriesId", n => { SeriesId = n.GetStringValue(); } },
                { "Stars", n => { Stars = n.GetDoubleValue(); } },
                { "StartTime", n => { StartTime = n.GetDateTimeOffsetValue(); } },
                { "SubPropNames", n => { SubPropNames = n.GetStringValue(); } },
                { "SubProps", n => { SubProps = n.GetIntValue(); } },
                { "SubTitle", n => { SubTitle = n.GetStringValue(); } },
                { "Title", n => { Title = n.GetStringValue(); } },
                { "TotalEpisodes", n => { TotalEpisodes = n.GetIntValue(); } },
                { "VideoPropNames", n => { VideoPropNames = n.GetStringValue(); } },
                { "VideoProps", n => { VideoProps = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateValue("Airdate", Airdate);
            writer.WriteObjectValue<global::MythTvApi.Dvr.Models.ArtworkInfoList>("Artwork", Artwork);
            writer.WriteStringValue("AudioPropNames", AudioPropNames);
            writer.WriteIntValue("AudioProps", AudioProps);
            writer.WriteObjectValue<global::MythTvApi.Dvr.Models.CastMemberList>("Cast", Cast);
            writer.WriteStringValue("Category", Category);
            writer.WriteStringValue("CatType", CatType);
            writer.WriteObjectValue<global::MythTvApi.Dvr.Models.ChannelInfo>("Channel", Channel);
            writer.WriteStringValue("Description", Description);
            writer.WriteDateTimeOffsetValue("EndTime", EndTime);
            writer.WriteIntValue("Episode", Episode);
            writer.WriteStringValue("FileName", FileName);
            writer.WriteLongValue("FileSize", FileSize);
            writer.WriteStringValue("HostName", HostName);
            writer.WriteStringValue("Inetref", Inetref);
            writer.WriteDateTimeOffsetValue("LastModified", LastModified);
            writer.WriteStringValue("ProgramFlagNames", ProgramFlagNames);
            writer.WriteIntValue("ProgramFlags", ProgramFlags);
            writer.WriteStringValue("ProgramId", ProgramId);
            writer.WriteObjectValue<global::MythTvApi.Dvr.Models.RecordingInfo>("Recording", Recording);
            writer.WriteIntValue("ReleaseYear", ReleaseYear);
            writer.WriteBoolValue("Repeat", Repeat);
            writer.WriteIntValue("Season", Season);
            writer.WriteStringValue("SeriesId", SeriesId);
            writer.WriteDoubleValue("Stars", Stars);
            writer.WriteDateTimeOffsetValue("StartTime", StartTime);
            writer.WriteStringValue("SubPropNames", SubPropNames);
            writer.WriteIntValue("SubProps", SubProps);
            writer.WriteStringValue("SubTitle", SubTitle);
            writer.WriteStringValue("Title", Title);
            writer.WriteIntValue("TotalEpisodes", TotalEpisodes);
            writer.WriteStringValue("VideoPropNames", VideoPropNames);
            writer.WriteIntValue("VideoProps", VideoProps);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
