// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MythTvApi.Dvr.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RecRuleFilterList : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The AsOf property</summary>
        public DateTimeOffset? AsOf { get; set; }
        /// <summary>The Count property</summary>
        public int? Count { get; set; }
        /// <summary>The ProtoVer property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProtoVer { get; set; }
#nullable restore
#else
        public string ProtoVer { get; set; }
#endif
        /// <summary>The RecRuleFilters property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MythTvApi.Dvr.Models.RecRuleFilter>? RecRuleFilters { get; set; }
#nullable restore
#else
        public List<global::MythTvApi.Dvr.Models.RecRuleFilter> RecRuleFilters { get; set; }
#endif
        /// <summary>The StartIndex property</summary>
        public int? StartIndex { get; set; }
        /// <summary>The TotalAvailable property</summary>
        public int? TotalAvailable { get; set; }
        /// <summary>The Version property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Version { get; set; }
#nullable restore
#else
        public string Version { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Dvr.Models.RecRuleFilterList"/> and sets the default values.
        /// </summary>
        public RecRuleFilterList()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Dvr.Models.RecRuleFilterList"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MythTvApi.Dvr.Models.RecRuleFilterList CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MythTvApi.Dvr.Models.RecRuleFilterList();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AsOf", n => { AsOf = n.GetDateTimeOffsetValue(); } },
                { "Count", n => { Count = n.GetIntValue(); } },
                { "ProtoVer", n => { ProtoVer = n.GetStringValue(); } },
                { "RecRuleFilters", n => { RecRuleFilters = n.GetCollectionOfObjectValues<global::MythTvApi.Dvr.Models.RecRuleFilter>(global::MythTvApi.Dvr.Models.RecRuleFilter.CreateFromDiscriminatorValue)?.AsList(); } },
                { "StartIndex", n => { StartIndex = n.GetIntValue(); } },
                { "TotalAvailable", n => { TotalAvailable = n.GetIntValue(); } },
                { "Version", n => { Version = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("AsOf", AsOf);
            writer.WriteIntValue("Count", Count);
            writer.WriteStringValue("ProtoVer", ProtoVer);
            writer.WriteCollectionOfObjectValues<global::MythTvApi.Dvr.Models.RecRuleFilter>("RecRuleFilters", RecRuleFilters);
            writer.WriteIntValue("StartIndex", StartIndex);
            writer.WriteIntValue("TotalAvailable", TotalAvailable);
            writer.WriteStringValue("Version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
