// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MythTvApi.Dvr.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RecRule : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The AutoCommflag property</summary>
        public bool? AutoCommflag { get; set; }
        /// <summary>The AutoExpire property</summary>
        public bool? AutoExpire { get; set; }
        /// <summary>The AutoExtend property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AutoExtend { get; set; }
#nullable restore
#else
        public string AutoExtend { get; set; }
#endif
        /// <summary>The AutoMetaLookup property</summary>
        public bool? AutoMetaLookup { get; set; }
        /// <summary>The AutoTranscode property</summary>
        public bool? AutoTranscode { get; set; }
        /// <summary>The AutoUserJob1 property</summary>
        public bool? AutoUserJob1 { get; set; }
        /// <summary>The AutoUserJob2 property</summary>
        public bool? AutoUserJob2 { get; set; }
        /// <summary>The AutoUserJob3 property</summary>
        public bool? AutoUserJob3 { get; set; }
        /// <summary>The AutoUserJob4 property</summary>
        public bool? AutoUserJob4 { get; set; }
        /// <summary>The AverageDelay property</summary>
        public int? AverageDelay { get; set; }
        /// <summary>The CallSign property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CallSign { get; set; }
#nullable restore
#else
        public string CallSign { get; set; }
#endif
        /// <summary>The Category property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Category { get; set; }
#nullable restore
#else
        public string Category { get; set; }
#endif
        /// <summary>The ChanId property</summary>
        public int? ChanId { get; set; }
        /// <summary>The Description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The DupIn property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DupIn { get; set; }
#nullable restore
#else
        public string DupIn { get; set; }
#endif
        /// <summary>The DupMethod property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DupMethod { get; set; }
#nullable restore
#else
        public string DupMethod { get; set; }
#endif
        /// <summary>The EndOffset property</summary>
        public int? EndOffset { get; set; }
        /// <summary>The EndTime property</summary>
        public DateTimeOffset? EndTime { get; set; }
        /// <summary>The Episode property</summary>
        public int? Episode { get; set; }
        /// <summary>The Filter property</summary>
        public int? Filter { get; set; }
        /// <summary>The FindDay property</summary>
        public int? FindDay { get; set; }
        /// <summary>The FindTime property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FindTime { get; set; }
#nullable restore
#else
        public string FindTime { get; set; }
#endif
        /// <summary>The Id property</summary>
        public int? Id { get; set; }
        /// <summary>The Inactive property</summary>
        public bool? Inactive { get; set; }
        /// <summary>The Inetref property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Inetref { get; set; }
#nullable restore
#else
        public string Inetref { get; set; }
#endif
        /// <summary>The LastDeleted property</summary>
        public DateTimeOffset? LastDeleted { get; set; }
        /// <summary>The LastRecorded property</summary>
        public DateTimeOffset? LastRecorded { get; set; }
        /// <summary>The MaxEpisodes property</summary>
        public int? MaxEpisodes { get; set; }
        /// <summary>The MaxNewest property</summary>
        public bool? MaxNewest { get; set; }
        /// <summary>The NewEpisOnly property</summary>
        public bool? NewEpisOnly { get; set; }
        /// <summary>The NextRecording property</summary>
        public DateTimeOffset? NextRecording { get; set; }
        /// <summary>The ParentId property</summary>
        public int? ParentId { get; set; }
        /// <summary>The PlayGroup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlayGroup { get; set; }
#nullable restore
#else
        public string PlayGroup { get; set; }
#endif
        /// <summary>The PreferredInput property</summary>
        public int? PreferredInput { get; set; }
        /// <summary>The ProgramId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProgramId { get; set; }
#nullable restore
#else
        public string ProgramId { get; set; }
#endif
        /// <summary>The RecGroup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RecGroup { get; set; }
#nullable restore
#else
        public string RecGroup { get; set; }
#endif
        /// <summary>The RecPriority property</summary>
        public int? RecPriority { get; set; }
        /// <summary>The RecProfile property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RecProfile { get; set; }
#nullable restore
#else
        public string RecProfile { get; set; }
#endif
        /// <summary>The SearchType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SearchType { get; set; }
#nullable restore
#else
        public string SearchType { get; set; }
#endif
        /// <summary>The Season property</summary>
        public int? Season { get; set; }
        /// <summary>The SeriesId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SeriesId { get; set; }
#nullable restore
#else
        public string SeriesId { get; set; }
#endif
        /// <summary>The StartOffset property</summary>
        public int? StartOffset { get; set; }
        /// <summary>The StartTime property</summary>
        public DateTimeOffset? StartTime { get; set; }
        /// <summary>The StorageGroup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StorageGroup { get; set; }
#nullable restore
#else
        public string StorageGroup { get; set; }
#endif
        /// <summary>The SubTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubTitle { get; set; }
#nullable restore
#else
        public string SubTitle { get; set; }
#endif
        /// <summary>The Title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The Transcoder property</summary>
        public int? Transcoder { get; set; }
        /// <summary>The Type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Dvr.Models.RecRule"/> and sets the default values.
        /// </summary>
        public RecRule()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Dvr.Models.RecRule"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MythTvApi.Dvr.Models.RecRule CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MythTvApi.Dvr.Models.RecRule();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AutoCommflag", n => { AutoCommflag = n.GetBoolValue(); } },
                { "AutoExpire", n => { AutoExpire = n.GetBoolValue(); } },
                { "AutoExtend", n => { AutoExtend = n.GetStringValue(); } },
                { "AutoMetaLookup", n => { AutoMetaLookup = n.GetBoolValue(); } },
                { "AutoTranscode", n => { AutoTranscode = n.GetBoolValue(); } },
                { "AutoUserJob1", n => { AutoUserJob1 = n.GetBoolValue(); } },
                { "AutoUserJob2", n => { AutoUserJob2 = n.GetBoolValue(); } },
                { "AutoUserJob3", n => { AutoUserJob3 = n.GetBoolValue(); } },
                { "AutoUserJob4", n => { AutoUserJob4 = n.GetBoolValue(); } },
                { "AverageDelay", n => { AverageDelay = n.GetIntValue(); } },
                { "CallSign", n => { CallSign = n.GetStringValue(); } },
                { "Category", n => { Category = n.GetStringValue(); } },
                { "ChanId", n => { ChanId = n.GetIntValue(); } },
                { "Description", n => { Description = n.GetStringValue(); } },
                { "DupIn", n => { DupIn = n.GetStringValue(); } },
                { "DupMethod", n => { DupMethod = n.GetStringValue(); } },
                { "EndOffset", n => { EndOffset = n.GetIntValue(); } },
                { "EndTime", n => { EndTime = n.GetDateTimeOffsetValue(); } },
                { "Episode", n => { Episode = n.GetIntValue(); } },
                { "Filter", n => { Filter = n.GetIntValue(); } },
                { "FindDay", n => { FindDay = n.GetIntValue(); } },
                { "FindTime", n => { FindTime = n.GetStringValue(); } },
                { "Id", n => { Id = n.GetIntValue(); } },
                { "Inactive", n => { Inactive = n.GetBoolValue(); } },
                { "Inetref", n => { Inetref = n.GetStringValue(); } },
                { "LastDeleted", n => { LastDeleted = n.GetDateTimeOffsetValue(); } },
                { "LastRecorded", n => { LastRecorded = n.GetDateTimeOffsetValue(); } },
                { "MaxEpisodes", n => { MaxEpisodes = n.GetIntValue(); } },
                { "MaxNewest", n => { MaxNewest = n.GetBoolValue(); } },
                { "NewEpisOnly", n => { NewEpisOnly = n.GetBoolValue(); } },
                { "NextRecording", n => { NextRecording = n.GetDateTimeOffsetValue(); } },
                { "ParentId", n => { ParentId = n.GetIntValue(); } },
                { "PlayGroup", n => { PlayGroup = n.GetStringValue(); } },
                { "PreferredInput", n => { PreferredInput = n.GetIntValue(); } },
                { "ProgramId", n => { ProgramId = n.GetStringValue(); } },
                { "RecGroup", n => { RecGroup = n.GetStringValue(); } },
                { "RecPriority", n => { RecPriority = n.GetIntValue(); } },
                { "RecProfile", n => { RecProfile = n.GetStringValue(); } },
                { "SearchType", n => { SearchType = n.GetStringValue(); } },
                { "Season", n => { Season = n.GetIntValue(); } },
                { "SeriesId", n => { SeriesId = n.GetStringValue(); } },
                { "StartOffset", n => { StartOffset = n.GetIntValue(); } },
                { "StartTime", n => { StartTime = n.GetDateTimeOffsetValue(); } },
                { "StorageGroup", n => { StorageGroup = n.GetStringValue(); } },
                { "SubTitle", n => { SubTitle = n.GetStringValue(); } },
                { "Title", n => { Title = n.GetStringValue(); } },
                { "Transcoder", n => { Transcoder = n.GetIntValue(); } },
                { "Type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("AutoCommflag", AutoCommflag);
            writer.WriteBoolValue("AutoExpire", AutoExpire);
            writer.WriteStringValue("AutoExtend", AutoExtend);
            writer.WriteBoolValue("AutoMetaLookup", AutoMetaLookup);
            writer.WriteBoolValue("AutoTranscode", AutoTranscode);
            writer.WriteBoolValue("AutoUserJob1", AutoUserJob1);
            writer.WriteBoolValue("AutoUserJob2", AutoUserJob2);
            writer.WriteBoolValue("AutoUserJob3", AutoUserJob3);
            writer.WriteBoolValue("AutoUserJob4", AutoUserJob4);
            writer.WriteIntValue("AverageDelay", AverageDelay);
            writer.WriteStringValue("CallSign", CallSign);
            writer.WriteStringValue("Category", Category);
            writer.WriteIntValue("ChanId", ChanId);
            writer.WriteStringValue("Description", Description);
            writer.WriteStringValue("DupIn", DupIn);
            writer.WriteStringValue("DupMethod", DupMethod);
            writer.WriteIntValue("EndOffset", EndOffset);
            writer.WriteDateTimeOffsetValue("EndTime", EndTime);
            writer.WriteIntValue("Episode", Episode);
            writer.WriteIntValue("Filter", Filter);
            writer.WriteIntValue("FindDay", FindDay);
            writer.WriteStringValue("FindTime", FindTime);
            writer.WriteIntValue("Id", Id);
            writer.WriteBoolValue("Inactive", Inactive);
            writer.WriteStringValue("Inetref", Inetref);
            writer.WriteDateTimeOffsetValue("LastDeleted", LastDeleted);
            writer.WriteDateTimeOffsetValue("LastRecorded", LastRecorded);
            writer.WriteIntValue("MaxEpisodes", MaxEpisodes);
            writer.WriteBoolValue("MaxNewest", MaxNewest);
            writer.WriteBoolValue("NewEpisOnly", NewEpisOnly);
            writer.WriteDateTimeOffsetValue("NextRecording", NextRecording);
            writer.WriteIntValue("ParentId", ParentId);
            writer.WriteStringValue("PlayGroup", PlayGroup);
            writer.WriteIntValue("PreferredInput", PreferredInput);
            writer.WriteStringValue("ProgramId", ProgramId);
            writer.WriteStringValue("RecGroup", RecGroup);
            writer.WriteIntValue("RecPriority", RecPriority);
            writer.WriteStringValue("RecProfile", RecProfile);
            writer.WriteStringValue("SearchType", SearchType);
            writer.WriteIntValue("Season", Season);
            writer.WriteStringValue("SeriesId", SeriesId);
            writer.WriteIntValue("StartOffset", StartOffset);
            writer.WriteDateTimeOffsetValue("StartTime", StartTime);
            writer.WriteStringValue("StorageGroup", StorageGroup);
            writer.WriteStringValue("SubTitle", SubTitle);
            writer.WriteStringValue("Title", Title);
            writer.WriteIntValue("Transcoder", Transcoder);
            writer.WriteStringValue("Type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
