// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace MythTvApi.Dvr.Dvr.GetProgramCategories
{
    /// <summary>
    /// Builds and executes requests for operations under \Dvr\GetProgramCategories
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetProgramCategoriesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Dvr.Dvr.GetProgramCategories.GetProgramCategoriesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetProgramCategoriesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Dvr/GetProgramCategories{?OnlyRecorded*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Dvr.Dvr.GetProgramCategories.GetProgramCategoriesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetProgramCategoriesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Dvr/GetProgramCategories{?OnlyRecorded*}", rawUrl)
        {
        }
        /// <summary>
        /// GET 
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Dvr.Dvr.GetProgramCategories.GetProgramCategoriesGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MythTvApi.Dvr.Dvr.GetProgramCategories.GetProgramCategoriesGetResponse?> GetAsync(Action<RequestConfiguration<global::MythTvApi.Dvr.Dvr.GetProgramCategories.GetProgramCategoriesRequestBuilder.GetProgramCategoriesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MythTvApi.Dvr.Dvr.GetProgramCategories.GetProgramCategoriesGetResponse> GetAsync(Action<RequestConfiguration<global::MythTvApi.Dvr.Dvr.GetProgramCategories.GetProgramCategoriesRequestBuilder.GetProgramCategoriesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::MythTvApi.Dvr.Dvr.GetProgramCategories.GetProgramCategoriesGetResponse>(requestInfo, global::MythTvApi.Dvr.Dvr.GetProgramCategories.GetProgramCategoriesGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// GET 
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MythTvApi.Dvr.Dvr.GetProgramCategories.GetProgramCategoriesRequestBuilder.GetProgramCategoriesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MythTvApi.Dvr.Dvr.GetProgramCategories.GetProgramCategoriesRequestBuilder.GetProgramCategoriesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Dvr.Dvr.GetProgramCategories.GetProgramCategoriesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::MythTvApi.Dvr.Dvr.GetProgramCategories.GetProgramCategoriesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::MythTvApi.Dvr.Dvr.GetProgramCategories.GetProgramCategoriesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// GET 
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GetProgramCategoriesRequestBuilderGetQueryParameters 
        {
            public bool? OnlyRecorded { get; set; }
        }
    }
}
#pragma warning restore CS0618
