// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace MythTvApi.Video.Video.GetVideoCutList
{
    /// <summary>
    /// Builds and executes requests for operations under \Video\GetVideoCutList
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetVideoCutListRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Video.Video.GetVideoCutList.GetVideoCutListRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetVideoCutListRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Video/GetVideoCutList{?Id*,IncludeFps*,OffsetType*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Video.Video.GetVideoCutList.GetVideoCutListRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetVideoCutListRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Video/GetVideoCutList{?Id*,IncludeFps*,OffsetType*}", rawUrl)
        {
        }
        /// <summary>
        /// GET 
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Video.Video.GetVideoCutList.GetVideoCutListGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MythTvApi.Video.Video.GetVideoCutList.GetVideoCutListGetResponse?> GetAsGetVideoCutListGetResponseAsync(Action<RequestConfiguration<global::MythTvApi.Video.Video.GetVideoCutList.GetVideoCutListRequestBuilder.GetVideoCutListRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MythTvApi.Video.Video.GetVideoCutList.GetVideoCutListGetResponse> GetAsGetVideoCutListGetResponseAsync(Action<RequestConfiguration<global::MythTvApi.Video.Video.GetVideoCutList.GetVideoCutListRequestBuilder.GetVideoCutListRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::MythTvApi.Video.Video.GetVideoCutList.GetVideoCutListGetResponse>(requestInfo, global::MythTvApi.Video.Video.GetVideoCutList.GetVideoCutListGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// GET 
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Video.Video.GetVideoCutList.GetVideoCutListResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use GetAsGetVideoCutListGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MythTvApi.Video.Video.GetVideoCutList.GetVideoCutListResponse?> GetAsync(Action<RequestConfiguration<global::MythTvApi.Video.Video.GetVideoCutList.GetVideoCutListRequestBuilder.GetVideoCutListRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MythTvApi.Video.Video.GetVideoCutList.GetVideoCutListResponse> GetAsync(Action<RequestConfiguration<global::MythTvApi.Video.Video.GetVideoCutList.GetVideoCutListRequestBuilder.GetVideoCutListRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::MythTvApi.Video.Video.GetVideoCutList.GetVideoCutListResponse>(requestInfo, global::MythTvApi.Video.Video.GetVideoCutList.GetVideoCutListResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// GET 
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MythTvApi.Video.Video.GetVideoCutList.GetVideoCutListRequestBuilder.GetVideoCutListRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MythTvApi.Video.Video.GetVideoCutList.GetVideoCutListRequestBuilder.GetVideoCutListRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Video.Video.GetVideoCutList.GetVideoCutListRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::MythTvApi.Video.Video.GetVideoCutList.GetVideoCutListRequestBuilder WithUrl(string rawUrl)
        {
            return new global::MythTvApi.Video.Video.GetVideoCutList.GetVideoCutListRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// GET 
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GetVideoCutListRequestBuilderGetQueryParameters 
        {
            public int? Id { get; set; }
            public bool? IncludeFps { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? OffsetType { get; set; }
#nullable restore
#else
            public string OffsetType { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GetVideoCutListRequestBuilderGetRequestConfiguration : RequestConfiguration<global::MythTvApi.Video.Video.GetVideoCutList.GetVideoCutListRequestBuilder.GetVideoCutListRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
