// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MythTvApi.Dvr.Dvr.GetRecordedCommBreak
{
    [Obsolete("This class is obsolete. Use GetRecordedCommBreakGetResponse instead.")]
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetRecordedCommBreakResponse : global::MythTvApi.Dvr.Dvr.GetRecordedCommBreak.GetRecordedCommBreakGetResponse, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Dvr.Dvr.GetRecordedCommBreak.GetRecordedCommBreakResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::MythTvApi.Dvr.Dvr.GetRecordedCommBreak.GetRecordedCommBreakResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MythTvApi.Dvr.Dvr.GetRecordedCommBreak.GetRecordedCommBreakResponse();
        }
    }
}
#pragma warning restore CS0618
