// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace MythTvApi.Guide.Guide.GetProgramGuide
{
    /// <summary>
    /// Builds and executes requests for operations under \Guide\GetProgramGuide
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetProgramGuideRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Guide.Guide.GetProgramGuide.GetProgramGuideRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetProgramGuideRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Guide/GetProgramGuide{?ChannelGroupId*,Count*,Details*,EndTime*,StartIndex*,StartTime*,WithInvisible*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Guide.Guide.GetProgramGuide.GetProgramGuideRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetProgramGuideRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Guide/GetProgramGuide{?ChannelGroupId*,Count*,Details*,EndTime*,StartIndex*,StartTime*,WithInvisible*}", rawUrl)
        {
        }
        /// <summary>
        /// GET 
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Guide.Guide.GetProgramGuide.GetProgramGuideGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MythTvApi.Guide.Guide.GetProgramGuide.GetProgramGuideGetResponse?> GetAsync(Action<RequestConfiguration<global::MythTvApi.Guide.Guide.GetProgramGuide.GetProgramGuideRequestBuilder.GetProgramGuideRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MythTvApi.Guide.Guide.GetProgramGuide.GetProgramGuideGetResponse> GetAsync(Action<RequestConfiguration<global::MythTvApi.Guide.Guide.GetProgramGuide.GetProgramGuideRequestBuilder.GetProgramGuideRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::MythTvApi.Guide.Guide.GetProgramGuide.GetProgramGuideGetResponse>(requestInfo, global::MythTvApi.Guide.Guide.GetProgramGuide.GetProgramGuideGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// GET 
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MythTvApi.Guide.Guide.GetProgramGuide.GetProgramGuideRequestBuilder.GetProgramGuideRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MythTvApi.Guide.Guide.GetProgramGuide.GetProgramGuideRequestBuilder.GetProgramGuideRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::MythTvApi.Guide.Guide.GetProgramGuide.GetProgramGuideRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::MythTvApi.Guide.Guide.GetProgramGuide.GetProgramGuideRequestBuilder WithUrl(string rawUrl)
        {
            return new global::MythTvApi.Guide.Guide.GetProgramGuide.GetProgramGuideRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// GET 
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GetProgramGuideRequestBuilderGetQueryParameters 
        {
            public int? ChannelGroupId { get; set; }
            public int? Count { get; set; }
            public bool? Details { get; set; }
            public DateTimeOffset? EndTime { get; set; }
            public int? StartIndex { get; set; }
            public DateTimeOffset? StartTime { get; set; }
            public bool? WithInvisible { get; set; }
        }
    }
}
#pragma warning restore CS0618
