// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using MythTvApi.Dvr.Dvr.AddDontRecordSchedule;
using MythTvApi.Dvr.Dvr.AddPlayGroup;
using MythTvApi.Dvr.Dvr.AddPowerPriority;
using MythTvApi.Dvr.Dvr.AddRecordSchedule;
using MythTvApi.Dvr.Dvr.AddRecordedCredits;
using MythTvApi.Dvr.Dvr.AddRecordedProgram;
using MythTvApi.Dvr.Dvr.AllowReRecord;
using MythTvApi.Dvr.Dvr.CheckPowerQuery;
using MythTvApi.Dvr.Dvr.DeleteRecording;
using MythTvApi.Dvr.Dvr.DisableRecordSchedule;
using MythTvApi.Dvr.Dvr.DupInToDescription;
using MythTvApi.Dvr.Dvr.DupInToString;
using MythTvApi.Dvr.Dvr.DupMethodToDescription;
using MythTvApi.Dvr.Dvr.DupMethodToString;
using MythTvApi.Dvr.Dvr.EnableRecordSchedule;
using MythTvApi.Dvr.Dvr.GetConflictList;
using MythTvApi.Dvr.Dvr.GetEncoderList;
using MythTvApi.Dvr.Dvr.GetExpiringList;
using MythTvApi.Dvr.Dvr.GetInputList;
using MythTvApi.Dvr.Dvr.GetLastPlayPos;
using MythTvApi.Dvr.Dvr.GetOldRecordedList;
using MythTvApi.Dvr.Dvr.GetPlayGroup;
using MythTvApi.Dvr.Dvr.GetPlayGroupList;
using MythTvApi.Dvr.Dvr.GetPowerPriorityList;
using MythTvApi.Dvr.Dvr.GetProgramCategories;
using MythTvApi.Dvr.Dvr.GetRecGroupList;
using MythTvApi.Dvr.Dvr.GetRecRuleFilterList;
using MythTvApi.Dvr.Dvr.GetRecStorageGroupList;
using MythTvApi.Dvr.Dvr.GetRecordSchedule;
using MythTvApi.Dvr.Dvr.GetRecordScheduleList;
using MythTvApi.Dvr.Dvr.GetRecorded;
using MythTvApi.Dvr.Dvr.GetRecordedCommBreak;
using MythTvApi.Dvr.Dvr.GetRecordedCutList;
using MythTvApi.Dvr.Dvr.GetRecordedList;
using MythTvApi.Dvr.Dvr.GetRecordedMarkup;
using MythTvApi.Dvr.Dvr.GetRecordedSeek;
using MythTvApi.Dvr.Dvr.GetSavedBookmark;
using MythTvApi.Dvr.Dvr.GetTitleInfoList;
using MythTvApi.Dvr.Dvr.GetTitleList;
using MythTvApi.Dvr.Dvr.GetUpcomingList;
using MythTvApi.Dvr.Dvr.ManageJobQueue;
using MythTvApi.Dvr.Dvr.ReactivateRecording;
using MythTvApi.Dvr.Dvr.RecStatusToDescription;
using MythTvApi.Dvr.Dvr.RecStatusToString;
using MythTvApi.Dvr.Dvr.RecTypeToDescription;
using MythTvApi.Dvr.Dvr.RecTypeToString;
using MythTvApi.Dvr.Dvr.RecordedIdForKey;
using MythTvApi.Dvr.Dvr.RecordedIdForPathname;
using MythTvApi.Dvr.Dvr.RemoveOldRecorded;
using MythTvApi.Dvr.Dvr.RemovePlayGroup;
using MythTvApi.Dvr.Dvr.RemovePowerPriority;
using MythTvApi.Dvr.Dvr.RemoveRecordSchedule;
using MythTvApi.Dvr.Dvr.RemoveRecorded;
using MythTvApi.Dvr.Dvr.RescheduleRecordings;
using MythTvApi.Dvr.Dvr.SetLastPlayPos;
using MythTvApi.Dvr.Dvr.SetRecordedMarkup;
using MythTvApi.Dvr.Dvr.SetSavedBookmark;
using MythTvApi.Dvr.Dvr.StopRecording;
using MythTvApi.Dvr.Dvr.UnDeleteRecording;
using MythTvApi.Dvr.Dvr.UpdateOldRecorded;
using MythTvApi.Dvr.Dvr.UpdatePlayGroup;
using MythTvApi.Dvr.Dvr.UpdatePowerPriority;
using MythTvApi.Dvr.Dvr.UpdateRecordSchedule;
using MythTvApi.Dvr.Dvr.UpdateRecordedMetadata;
using MythTvApi.Dvr.Dvr.UpdateRecordedWatchedStatus;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MythTvApi.Dvr.Dvr
{
    /// <summary>
    /// Builds and executes requests for operations under \Dvr
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DvrRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The AddDontRecordSchedule property</summary>
        public global::MythTvApi.Dvr.Dvr.AddDontRecordSchedule.AddDontRecordScheduleRequestBuilder AddDontRecordSchedule
        {
            get => new global::MythTvApi.Dvr.Dvr.AddDontRecordSchedule.AddDontRecordScheduleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The AddPlayGroup property</summary>
        public global::MythTvApi.Dvr.Dvr.AddPlayGroup.AddPlayGroupRequestBuilder AddPlayGroup
        {
            get => new global::MythTvApi.Dvr.Dvr.AddPlayGroup.AddPlayGroupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The AddPowerPriority property</summary>
        public global::MythTvApi.Dvr.Dvr.AddPowerPriority.AddPowerPriorityRequestBuilder AddPowerPriority
        {
            get => new global::MythTvApi.Dvr.Dvr.AddPowerPriority.AddPowerPriorityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The AddRecordedCredits property</summary>
        public global::MythTvApi.Dvr.Dvr.AddRecordedCredits.AddRecordedCreditsRequestBuilder AddRecordedCredits
        {
            get => new global::MythTvApi.Dvr.Dvr.AddRecordedCredits.AddRecordedCreditsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The AddRecordedProgram property</summary>
        public global::MythTvApi.Dvr.Dvr.AddRecordedProgram.AddRecordedProgramRequestBuilder AddRecordedProgram
        {
            get => new global::MythTvApi.Dvr.Dvr.AddRecordedProgram.AddRecordedProgramRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The AddRecordSchedule property</summary>
        public global::MythTvApi.Dvr.Dvr.AddRecordSchedule.AddRecordScheduleRequestBuilder AddRecordSchedule
        {
            get => new global::MythTvApi.Dvr.Dvr.AddRecordSchedule.AddRecordScheduleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The AllowReRecord property</summary>
        public global::MythTvApi.Dvr.Dvr.AllowReRecord.AllowReRecordRequestBuilder AllowReRecord
        {
            get => new global::MythTvApi.Dvr.Dvr.AllowReRecord.AllowReRecordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The CheckPowerQuery property</summary>
        public global::MythTvApi.Dvr.Dvr.CheckPowerQuery.CheckPowerQueryRequestBuilder CheckPowerQuery
        {
            get => new global::MythTvApi.Dvr.Dvr.CheckPowerQuery.CheckPowerQueryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The DeleteRecording property</summary>
        public global::MythTvApi.Dvr.Dvr.DeleteRecording.DeleteRecordingRequestBuilder DeleteRecording
        {
            get => new global::MythTvApi.Dvr.Dvr.DeleteRecording.DeleteRecordingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The DisableRecordSchedule property</summary>
        public global::MythTvApi.Dvr.Dvr.DisableRecordSchedule.DisableRecordScheduleRequestBuilder DisableRecordSchedule
        {
            get => new global::MythTvApi.Dvr.Dvr.DisableRecordSchedule.DisableRecordScheduleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The DupInToDescription property</summary>
        public global::MythTvApi.Dvr.Dvr.DupInToDescription.DupInToDescriptionRequestBuilder DupInToDescription
        {
            get => new global::MythTvApi.Dvr.Dvr.DupInToDescription.DupInToDescriptionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The DupInToString property</summary>
        public global::MythTvApi.Dvr.Dvr.DupInToString.DupInToStringRequestBuilder DupInToString
        {
            get => new global::MythTvApi.Dvr.Dvr.DupInToString.DupInToStringRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The DupMethodToDescription property</summary>
        public global::MythTvApi.Dvr.Dvr.DupMethodToDescription.DupMethodToDescriptionRequestBuilder DupMethodToDescription
        {
            get => new global::MythTvApi.Dvr.Dvr.DupMethodToDescription.DupMethodToDescriptionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The DupMethodToString property</summary>
        public global::MythTvApi.Dvr.Dvr.DupMethodToString.DupMethodToStringRequestBuilder DupMethodToString
        {
            get => new global::MythTvApi.Dvr.Dvr.DupMethodToString.DupMethodToStringRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The EnableRecordSchedule property</summary>
        public global::MythTvApi.Dvr.Dvr.EnableRecordSchedule.EnableRecordScheduleRequestBuilder EnableRecordSchedule
        {
            get => new global::MythTvApi.Dvr.Dvr.EnableRecordSchedule.EnableRecordScheduleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetConflictList property</summary>
        public global::MythTvApi.Dvr.Dvr.GetConflictList.GetConflictListRequestBuilder GetConflictList
        {
            get => new global::MythTvApi.Dvr.Dvr.GetConflictList.GetConflictListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetEncoderList property</summary>
        public global::MythTvApi.Dvr.Dvr.GetEncoderList.GetEncoderListRequestBuilder GetEncoderList
        {
            get => new global::MythTvApi.Dvr.Dvr.GetEncoderList.GetEncoderListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetExpiringList property</summary>
        public global::MythTvApi.Dvr.Dvr.GetExpiringList.GetExpiringListRequestBuilder GetExpiringList
        {
            get => new global::MythTvApi.Dvr.Dvr.GetExpiringList.GetExpiringListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetInputList property</summary>
        public global::MythTvApi.Dvr.Dvr.GetInputList.GetInputListRequestBuilder GetInputList
        {
            get => new global::MythTvApi.Dvr.Dvr.GetInputList.GetInputListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetLastPlayPos property</summary>
        public global::MythTvApi.Dvr.Dvr.GetLastPlayPos.GetLastPlayPosRequestBuilder GetLastPlayPos
        {
            get => new global::MythTvApi.Dvr.Dvr.GetLastPlayPos.GetLastPlayPosRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetOldRecordedList property</summary>
        public global::MythTvApi.Dvr.Dvr.GetOldRecordedList.GetOldRecordedListRequestBuilder GetOldRecordedList
        {
            get => new global::MythTvApi.Dvr.Dvr.GetOldRecordedList.GetOldRecordedListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetPlayGroup property</summary>
        public global::MythTvApi.Dvr.Dvr.GetPlayGroup.GetPlayGroupRequestBuilder GetPlayGroup
        {
            get => new global::MythTvApi.Dvr.Dvr.GetPlayGroup.GetPlayGroupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetPlayGroupList property</summary>
        public global::MythTvApi.Dvr.Dvr.GetPlayGroupList.GetPlayGroupListRequestBuilder GetPlayGroupList
        {
            get => new global::MythTvApi.Dvr.Dvr.GetPlayGroupList.GetPlayGroupListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetPowerPriorityList property</summary>
        public global::MythTvApi.Dvr.Dvr.GetPowerPriorityList.GetPowerPriorityListRequestBuilder GetPowerPriorityList
        {
            get => new global::MythTvApi.Dvr.Dvr.GetPowerPriorityList.GetPowerPriorityListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetProgramCategories property</summary>
        public global::MythTvApi.Dvr.Dvr.GetProgramCategories.GetProgramCategoriesRequestBuilder GetProgramCategories
        {
            get => new global::MythTvApi.Dvr.Dvr.GetProgramCategories.GetProgramCategoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetRecGroupList property</summary>
        public global::MythTvApi.Dvr.Dvr.GetRecGroupList.GetRecGroupListRequestBuilder GetRecGroupList
        {
            get => new global::MythTvApi.Dvr.Dvr.GetRecGroupList.GetRecGroupListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetRecorded property</summary>
        public global::MythTvApi.Dvr.Dvr.GetRecorded.GetRecordedRequestBuilder GetRecorded
        {
            get => new global::MythTvApi.Dvr.Dvr.GetRecorded.GetRecordedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetRecordedCommBreak property</summary>
        public global::MythTvApi.Dvr.Dvr.GetRecordedCommBreak.GetRecordedCommBreakRequestBuilder GetRecordedCommBreak
        {
            get => new global::MythTvApi.Dvr.Dvr.GetRecordedCommBreak.GetRecordedCommBreakRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetRecordedCutList property</summary>
        public global::MythTvApi.Dvr.Dvr.GetRecordedCutList.GetRecordedCutListRequestBuilder GetRecordedCutList
        {
            get => new global::MythTvApi.Dvr.Dvr.GetRecordedCutList.GetRecordedCutListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetRecordedList property</summary>
        public global::MythTvApi.Dvr.Dvr.GetRecordedList.GetRecordedListRequestBuilder GetRecordedList
        {
            get => new global::MythTvApi.Dvr.Dvr.GetRecordedList.GetRecordedListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetRecordedMarkup property</summary>
        public global::MythTvApi.Dvr.Dvr.GetRecordedMarkup.GetRecordedMarkupRequestBuilder GetRecordedMarkup
        {
            get => new global::MythTvApi.Dvr.Dvr.GetRecordedMarkup.GetRecordedMarkupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetRecordedSeek property</summary>
        public global::MythTvApi.Dvr.Dvr.GetRecordedSeek.GetRecordedSeekRequestBuilder GetRecordedSeek
        {
            get => new global::MythTvApi.Dvr.Dvr.GetRecordedSeek.GetRecordedSeekRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetRecordSchedule property</summary>
        public global::MythTvApi.Dvr.Dvr.GetRecordSchedule.GetRecordScheduleRequestBuilder GetRecordSchedule
        {
            get => new global::MythTvApi.Dvr.Dvr.GetRecordSchedule.GetRecordScheduleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetRecordScheduleList property</summary>
        public global::MythTvApi.Dvr.Dvr.GetRecordScheduleList.GetRecordScheduleListRequestBuilder GetRecordScheduleList
        {
            get => new global::MythTvApi.Dvr.Dvr.GetRecordScheduleList.GetRecordScheduleListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetRecRuleFilterList property</summary>
        public global::MythTvApi.Dvr.Dvr.GetRecRuleFilterList.GetRecRuleFilterListRequestBuilder GetRecRuleFilterList
        {
            get => new global::MythTvApi.Dvr.Dvr.GetRecRuleFilterList.GetRecRuleFilterListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetRecStorageGroupList property</summary>
        public global::MythTvApi.Dvr.Dvr.GetRecStorageGroupList.GetRecStorageGroupListRequestBuilder GetRecStorageGroupList
        {
            get => new global::MythTvApi.Dvr.Dvr.GetRecStorageGroupList.GetRecStorageGroupListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetSavedBookmark property</summary>
        public global::MythTvApi.Dvr.Dvr.GetSavedBookmark.GetSavedBookmarkRequestBuilder GetSavedBookmark
        {
            get => new global::MythTvApi.Dvr.Dvr.GetSavedBookmark.GetSavedBookmarkRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetTitleInfoList property</summary>
        public global::MythTvApi.Dvr.Dvr.GetTitleInfoList.GetTitleInfoListRequestBuilder GetTitleInfoList
        {
            get => new global::MythTvApi.Dvr.Dvr.GetTitleInfoList.GetTitleInfoListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetTitleList property</summary>
        public global::MythTvApi.Dvr.Dvr.GetTitleList.GetTitleListRequestBuilder GetTitleList
        {
            get => new global::MythTvApi.Dvr.Dvr.GetTitleList.GetTitleListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetUpcomingList property</summary>
        public global::MythTvApi.Dvr.Dvr.GetUpcomingList.GetUpcomingListRequestBuilder GetUpcomingList
        {
            get => new global::MythTvApi.Dvr.Dvr.GetUpcomingList.GetUpcomingListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ManageJobQueue property</summary>
        public global::MythTvApi.Dvr.Dvr.ManageJobQueue.ManageJobQueueRequestBuilder ManageJobQueue
        {
            get => new global::MythTvApi.Dvr.Dvr.ManageJobQueue.ManageJobQueueRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ReactivateRecording property</summary>
        public global::MythTvApi.Dvr.Dvr.ReactivateRecording.ReactivateRecordingRequestBuilder ReactivateRecording
        {
            get => new global::MythTvApi.Dvr.Dvr.ReactivateRecording.ReactivateRecordingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The RecordedIdForKey property</summary>
        public global::MythTvApi.Dvr.Dvr.RecordedIdForKey.RecordedIdForKeyRequestBuilder RecordedIdForKey
        {
            get => new global::MythTvApi.Dvr.Dvr.RecordedIdForKey.RecordedIdForKeyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The RecordedIdForPathname property</summary>
        public global::MythTvApi.Dvr.Dvr.RecordedIdForPathname.RecordedIdForPathnameRequestBuilder RecordedIdForPathname
        {
            get => new global::MythTvApi.Dvr.Dvr.RecordedIdForPathname.RecordedIdForPathnameRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The RecStatusToDescription property</summary>
        public global::MythTvApi.Dvr.Dvr.RecStatusToDescription.RecStatusToDescriptionRequestBuilder RecStatusToDescription
        {
            get => new global::MythTvApi.Dvr.Dvr.RecStatusToDescription.RecStatusToDescriptionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The RecStatusToString property</summary>
        public global::MythTvApi.Dvr.Dvr.RecStatusToString.RecStatusToStringRequestBuilder RecStatusToString
        {
            get => new global::MythTvApi.Dvr.Dvr.RecStatusToString.RecStatusToStringRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The RecTypeToDescription property</summary>
        public global::MythTvApi.Dvr.Dvr.RecTypeToDescription.RecTypeToDescriptionRequestBuilder RecTypeToDescription
        {
            get => new global::MythTvApi.Dvr.Dvr.RecTypeToDescription.RecTypeToDescriptionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The RecTypeToString property</summary>
        public global::MythTvApi.Dvr.Dvr.RecTypeToString.RecTypeToStringRequestBuilder RecTypeToString
        {
            get => new global::MythTvApi.Dvr.Dvr.RecTypeToString.RecTypeToStringRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The RemoveOldRecorded property</summary>
        public global::MythTvApi.Dvr.Dvr.RemoveOldRecorded.RemoveOldRecordedRequestBuilder RemoveOldRecorded
        {
            get => new global::MythTvApi.Dvr.Dvr.RemoveOldRecorded.RemoveOldRecordedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The RemovePlayGroup property</summary>
        public global::MythTvApi.Dvr.Dvr.RemovePlayGroup.RemovePlayGroupRequestBuilder RemovePlayGroup
        {
            get => new global::MythTvApi.Dvr.Dvr.RemovePlayGroup.RemovePlayGroupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The RemovePowerPriority property</summary>
        public global::MythTvApi.Dvr.Dvr.RemovePowerPriority.RemovePowerPriorityRequestBuilder RemovePowerPriority
        {
            get => new global::MythTvApi.Dvr.Dvr.RemovePowerPriority.RemovePowerPriorityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The RemoveRecorded property</summary>
        public global::MythTvApi.Dvr.Dvr.RemoveRecorded.RemoveRecordedRequestBuilder RemoveRecorded
        {
            get => new global::MythTvApi.Dvr.Dvr.RemoveRecorded.RemoveRecordedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The RemoveRecordSchedule property</summary>
        public global::MythTvApi.Dvr.Dvr.RemoveRecordSchedule.RemoveRecordScheduleRequestBuilder RemoveRecordSchedule
        {
            get => new global::MythTvApi.Dvr.Dvr.RemoveRecordSchedule.RemoveRecordScheduleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The RescheduleRecordings property</summary>
        public global::MythTvApi.Dvr.Dvr.RescheduleRecordings.RescheduleRecordingsRequestBuilder RescheduleRecordings
        {
            get => new global::MythTvApi.Dvr.Dvr.RescheduleRecordings.RescheduleRecordingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The SetLastPlayPos property</summary>
        public global::MythTvApi.Dvr.Dvr.SetLastPlayPos.SetLastPlayPosRequestBuilder SetLastPlayPos
        {
            get => new global::MythTvApi.Dvr.Dvr.SetLastPlayPos.SetLastPlayPosRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The SetRecordedMarkup property</summary>
        public global::MythTvApi.Dvr.Dvr.SetRecordedMarkup.SetRecordedMarkupRequestBuilder SetRecordedMarkup
        {
            get => new global::MythTvApi.Dvr.Dvr.SetRecordedMarkup.SetRecordedMarkupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The SetSavedBookmark property</summary>
        public global::MythTvApi.Dvr.Dvr.SetSavedBookmark.SetSavedBookmarkRequestBuilder SetSavedBookmark
        {
            get => new global::MythTvApi.Dvr.Dvr.SetSavedBookmark.SetSavedBookmarkRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The StopRecording property</summary>
        public global::MythTvApi.Dvr.Dvr.StopRecording.StopRecordingRequestBuilder StopRecording
        {
            get => new global::MythTvApi.Dvr.Dvr.StopRecording.StopRecordingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The UnDeleteRecording property</summary>
        public global::MythTvApi.Dvr.Dvr.UnDeleteRecording.UnDeleteRecordingRequestBuilder UnDeleteRecording
        {
            get => new global::MythTvApi.Dvr.Dvr.UnDeleteRecording.UnDeleteRecordingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The UpdateOldRecorded property</summary>
        public global::MythTvApi.Dvr.Dvr.UpdateOldRecorded.UpdateOldRecordedRequestBuilder UpdateOldRecorded
        {
            get => new global::MythTvApi.Dvr.Dvr.UpdateOldRecorded.UpdateOldRecordedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The UpdatePlayGroup property</summary>
        public global::MythTvApi.Dvr.Dvr.UpdatePlayGroup.UpdatePlayGroupRequestBuilder UpdatePlayGroup
        {
            get => new global::MythTvApi.Dvr.Dvr.UpdatePlayGroup.UpdatePlayGroupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The UpdatePowerPriority property</summary>
        public global::MythTvApi.Dvr.Dvr.UpdatePowerPriority.UpdatePowerPriorityRequestBuilder UpdatePowerPriority
        {
            get => new global::MythTvApi.Dvr.Dvr.UpdatePowerPriority.UpdatePowerPriorityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The UpdateRecordedMetadata property</summary>
        public global::MythTvApi.Dvr.Dvr.UpdateRecordedMetadata.UpdateRecordedMetadataRequestBuilder UpdateRecordedMetadata
        {
            get => new global::MythTvApi.Dvr.Dvr.UpdateRecordedMetadata.UpdateRecordedMetadataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The UpdateRecordedWatchedStatus property</summary>
        public global::MythTvApi.Dvr.Dvr.UpdateRecordedWatchedStatus.UpdateRecordedWatchedStatusRequestBuilder UpdateRecordedWatchedStatus
        {
            get => new global::MythTvApi.Dvr.Dvr.UpdateRecordedWatchedStatus.UpdateRecordedWatchedStatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The UpdateRecordSchedule property</summary>
        public global::MythTvApi.Dvr.Dvr.UpdateRecordSchedule.UpdateRecordScheduleRequestBuilder UpdateRecordSchedule
        {
            get => new global::MythTvApi.Dvr.Dvr.UpdateRecordSchedule.UpdateRecordScheduleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Dvr.Dvr.DvrRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DvrRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Dvr", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MythTvApi.Dvr.Dvr.DvrRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DvrRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Dvr", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
